Repository ministryofjustice/laa-submit-crime-forms, pull requests merged in 2024-11, with the labels that each got.

#1273 CRM457-2038 Accessibility issues on Disbursement cost page
  app/forms/nsm/steps/claim_details_form.rb
  app/forms/nsm/steps/disbursement_cost_form.rb
  app/forms/nsm/steps/hearing_details_form.rb
  app/forms/nsm/steps/letters_calls_form.rb
  app/models/concerns/letters_and_calls_costs.rb
  app/views/nsm/steps/claim_details/edit.html.erb
  app/views/nsm/steps/disbursement_cost/edit.html.erb
  app/views/nsm/steps/hearing_details/edit.html.erb
  app/views/nsm/steps/letters_calls/edit.html.erb
  config/locales/en/errors.yml
  config/locales/en/nsm/steps.yml
  gems/laa_multi_step_forms/app/attributes/type/fully_validatable_decimal.rb
  gems/laa_multi_step_forms/config/initializers/attribute_types.rb
  gems/laa_multi_step_forms/spec/attributes/type/fully_validatable_decimal_spec.rb
  gems/laa_multi_step_forms/spec/validators/is_a_number_validator_spec.rb
  spec/forms/nsm/steps/disbursements_cost_form_spec.rb
  spec/forms/nsm/steps/letters_calls_form_spec.rb
  spec/system/nsm/disbursements_spec.rb
Labels: ready for review

#1272 [CRM457-2103] PA Provider: Search and filter
  app/forms/search_form.rb
  app/views/layouts/prior_authority.html.erb
  app/views/layouts/prior_authority/_primary_navigation.html.erb
  app/views/nsm/claims/search.html.erb
  app/views/prior_authority/applications/search.html.erb
  app/views/shared/_search.html.erb
  config/locales/en.yml
  config/locales/en/nsm.yml
  config/locales/en/nsm/search.yml
  config/locales/en/prior_authority/search.yml
  spec/system/search_spec.rb
Labels: In QA

#1295 CRM457-2251: Resolve Snyk issue
  package.json
  yarn.lock
Labels: approved

#1305 CRM457-2276: Do things synchronously
  .env.test
  app/controllers/prior_authority/steps/submission_confirmation_controller.rb
  app/forms/nsm/steps/solicitor_declaration_form.rb
  app/forms/prior_authority/steps/check_answers_form.rb
  app/jobs/submit_to_app_store.rb
  app/services/app_store_client.rb
  app/services/app_store_update_processor.rb
  spec/forms/nsm/steps/solicitor_declaration_form_spec.rb
  spec/forms/prior_authority/steps/check_answers_form_spec.rb
  spec/jobs/submit_to_app_store_spec.rb
  spec/services/app_store_client_spec.rb
  spec/system/nsm/solicitor_declaration_spec.rb
  spec/system/prior_authority/check_your_answers/sent_back_for_correct_info_spec.rb
  spec/system/prior_authority/check_your_answers/submission_spec.rb
Labels: approved

#1320 CRM457-2315: JS can deal with errors that don't have message JSON
  app/javascript/multi-file-upload.js
Labels: ready for review

#1318 CRM457-2288: Update task list to handle youth court changes
  app/controllers/nsm/steps/solicitor_declaration_controller.rb
  app/forms/nsm/steps/case_category_form.rb
  app/forms/nsm/steps/claim_type_form.rb
  app/forms/nsm/steps/hearing_details_form.rb
  app/forms/nsm/steps/office_area_form.rb
  app/forms/nsm/steps/youth_court_claim_additional_fee_form.rb
  app/lib/constants.rb
  app/models/claim.rb
  app/presenters/nsm/start_page.rb
  app/presenters/nsm/tasks/case_disposal.rb
  app/presenters/nsm/tasks/case_outcome.rb
  app/presenters/tasks/generic.rb
  app/services/decisions/back_decision_tree.rb
  app/services/decisions/decision_tree.rb
  app/views/nsm/steps/case_outcome/edit.html.erb
  config/locales/en/tasklist.yml
  lib/test_data/nsm_builder.rb
  spec/controllers/nsm/steps/case_category_controller_spec.rb
  spec/controllers/nsm/steps/case_outcome_controller_spec.rb
  spec/decisions/decision_tree_spec.rb
  spec/factories/claims.rb
  spec/forms/nsm/steps/case_category_form_spec.rb
  spec/forms/nsm/steps/claim_type_form_spec.rb
  spec/lib/test_data/nsm_builder_spec.rb
  spec/presenter/nsm/steps/case_disposal_presenter_spec.rb
  spec/presenter/nsm/steps/case_outcome_presenter_spec.rb
  spec/system/nsm/youth_court_claim_additional_fee_spec.rb
Labels: approved
