Repository ministryofjustice/laa-submit-crime-forms, pull requests merged in 2024-04, with the labels that each got.

#682 CRM457-1188: Move error summary
  app/views/prior_authority/steps/alternative_quotes/_with_alternative_quotes.html.erb
Labels: approved

#684 CRM457-1200: Add fallback translation for all date validation errors
  config/locales/en/errors.yml
  spec/forms/prior_authority/steps/hearing_detail_form_spec.rb
Labels: approved

#683 Stop referring to event class names in payload
  app/services/prior_authority/assessment_syncer.rb
  app/services/submit_to_app_store/prior_authority/event_builder.rb
  spec/jobs/pull_updates_spec.rb
  spec/services/prior_authority/assessment_syncer_spec.rb
  spec/services/submit_to_app_store/prior_authority/event_builder_spec.rb
Labels: approved

#685 CRM457-1285: Specify which hosts are allowed
  config/environments/production.rb
  helm_deploy/templates/deployment.yaml
Labels: approved

#688 CRM457-1298: Stop using turbo-links
  app/javascript/application.js
Labels: approved

#686 Crm457 1281/randomise test data
  Gemfile
  Gemfile.lock
  app/models/application_record.rb
  spec/factories/claims.rb
  spec/factories/defendants.rb
  spec/factories/disbursements.rb
  spec/factories/work_items.rb
  spec/mailers/nsm/submission_mailer_spec.rb
  spec/mailers/prior_authority/submission_mailer_spec.rb
  spec/presenters/nsm/check_answers/case_details_card_spec.rb
  spec/presenters/nsm/check_answers/claim_type_card_spec.rb
  spec/presenters/nsm/check_answers/hearing_details_card_spec.rb
  spec/services/submit_to_app_store/nsm_payload_builder_spec.rb
  spec/services/submit_to_app_store/prior_authority_payload_builder_spec.rb
  spec/support/json_checker.rb
Labels: approved

#689 Crm457 1287 update azure authentication
  app/services/app_store_token_provider.rb
  dartsass:build
  docs/development-e2e-setup.md
  helm_deploy/templates/deployment-worker.yaml
  helm_deploy/templates/deployment.yaml
Labels: approved

#691 CRM457-1181: Stop using combined name fields
  app/forms/nsm/steps/firm_details/solicitor_form.rb
  app/forms/prior_authority/steps/alternative_quotes/detail_form.rb
  app/forms/prior_authority/steps/case_contact/solicitor_form.rb
  app/forms/prior_authority/steps/primary_quote_form.rb
  app/models/quote.rb
  app/models/solicitor.rb
  app/presenters/nsm/check_answers/your_details_card.rb
  app/services/submit_to_app_store/nsm_payload_builder.rb
  app/services/submit_to_app_store/prior_authority/quote_payload_builder.rb
  app/services/submit_to_app_store/prior_authority/solicitor_payload_builder.rb
  app/views/nsm/steps/firm_details/edit.html.erb
  app/views/prior_authority/steps/alternative_quote_details/edit.html.erb
  app/views/prior_authority/steps/case_contact/edit.html.erb
  app/views/prior_authority/steps/client_detail/edit.html.erb
  app/views/prior_authority/steps/primary_quote/edit.html.erb
  config/locales/en/errors.yml
  config/locales/en/helpers.yml
  config/locales/en/nsm/check_answers.yml
  config/locales/en/prior_authority/alternative_quotes.yml
  config/locales/en/prior_authority/check_answers.yml
  config/locales/en/prior_authority/steps.yml
  db/migrate/20240404094407_split_contact_full_names.rb
  db/schema.rb
  gems/laa_multi_step_forms/config/locales/errors.yml
  spec/factories/quote.rb
  spec/factories/solicitors.rb
  spec/forms/nsm/steps/firm_details/solicitor_form_spec.rb
  spec/forms/nsm/steps/firm_details_form_spec.rb
  spec/forms/prior_authority/steps/alternative_quotes/detail_form_spec.rb
  spec/forms/prior_authority/steps/case_contact/solicitor_form_spec.rb
  spec/forms/prior_authority/steps/case_contact_form_spec.rb
  spec/forms/prior_authority/steps/primary_quote_form_spec.rb
  spec/presenters/nsm/check_answers/your_details_card_spec.rb
  spec/presenters/prior_authority/check_answers/alternative_quotes_card_spec.rb
  spec/presenters/prior_authority/check_answers/case_contact_card_spec.rb
  spec/presenters/prior_authority/check_answers/primary_quote_card_spec.rb
  spec/services/submit_to_app_store/nsm_payload_builder_spec.rb
  spec/services/submit_to_app_store/prior_authority/event_builder_spec.rb
  spec/services/submit_to_app_store/prior_authority_payload_builder_spec.rb
  spec/system/nsm/firm_details_spec.rb
  spec/system/nsm/start_page_spec.rb
  spec/system/prior_authority/alternative_quotes_spec.rb
  spec/system/prior_authority/case_contact_spec.rb
  spec/system/prior_authority/check_your_answers/no_prison_law_spec.rb
  spec/system/prior_authority/primary_quote_spec.rb
  spec/system/support/prior_authority/step_helpers.rb
Labels: approved

#692 Fix assessment syncer error handling
  app/services/prior_authority/assessment_syncer.rb
  spec/jobs/pull_updates_spec.rb
Labels: approved

#693 CRM457-1303: Manual sync trigger
  .env.development
  .env.test
  app/controllers/sync_controller.rb
  config/routes.rb
  helm_deploy/templates/deployment.yaml
  helm_deploy/values-dev.yaml
  helm_deploy/values-prod.yaml
  helm_deploy/values-uat.yaml
  spec/requests/sync_spec.rb
Labels: ready for review

#694 CRM457-1181 QA: Update error messages
  app/forms/prior_authority/steps/case_contact_form.rb
  config/locales/en/errors.yml
  config/locales/en/prior_authority/alternative_quotes.yml
  spec/forms/prior_authority/steps/case_contact/solicitor_form_spec.rb
  spec/forms/prior_authority/steps/case_contact_form_spec.rb
  spec/forms/prior_authority/steps/primary_quote_form_spec.rb
  spec/system/prior_authority/alternative_quotes_spec.rb
  spec/system/prior_authority/case_contact_spec.rb
  spec/system/prior_authority/primary_quote_spec.rb
Labels: approved, In QA

#680 CRM457-1281 - build test data
  .rubocop.yml
  db/schema.rb
  gems/laa_multi_step_forms/.rubocop.yml
  lib/tasks/submit_dummy_data.rake
  lib/tasks/submit_dummy_pa_data.rake
  lib/test_data/nsm_builder.rb
  spec/factories/claims.rb
  spec/factories/disbursements.rb
  spec/factories/work_items.rb
  spec/lib/tasks/submit_dummy_data_spec.rb
  spec/lib/tasks/submit_dummy_pa_data_spec.rb
  spec/lib/test_data/nsm_builder_spec.rb
  spec/presenters/nsm/check_answers/case_details_card_spec.rb
  spec/services/submit_to_app_store/nsm_payload_builder_spec.rb
Labels: WIP

#695 CRM457-887: Control whether search engine indexing is allowed
  app/controllers/robots_controller.rb
  app/views/robots/allow.text
  app/views/robots/disallow.text
  config/routes.rb
  gems/laa_multi_step_forms/app/views/layouts/govuk_template.html.erb
  helm_deploy/templates/deployment.yaml
  helm_deploy/values-dev.yaml
  helm_deploy/values-prod.yaml
  helm_deploy/values-uat.yaml
  public/robots.txt
  spec/requests/robots_spec.rb
Labels: approved

#668 CRM457-1196: Application details in provider_updated state
  app/controllers/prior_authority/applications_controller.rb
  app/controllers/prior_authority/downloads_controller.rb
  app/helpers/tag_helper.rb
  app/models/prior_authority_application.rb
  app/presenters/prior_authority/check_answers/compact_further_information_card.rb
  app/presenters/prior_authority/check_answers/report.rb
  app/services/submit_to_app_store/prior_authority/event_builder.rb
  app/views/prior_authority/applications/state_summaries/_provider_updated.html.erb
  config/locales/en/prior_authority.yml
  config/locales/en/prior_authority/check_answers.yml
  config/routes.rb
  spec/services/submit_to_app_store/prior_authority/event_builder_spec.rb
  spec/system/prior_authority/view_applications_spec.rb
Labels: approved

#681 CRM457-1173: Stop casting date inputs to integers automatically
  app/views/nsm/steps/case_details/edit.html.erb
  app/views/nsm/steps/case_disposal/edit.html.erb
  app/views/nsm/steps/claim_details/edit.html.erb
  app/views/nsm/steps/claim_type/edit.html.erb
  app/views/nsm/steps/disbursement_type/edit.html.erb
  app/views/nsm/steps/hearing_details/edit.html.erb
  app/views/nsm/steps/reason_for_claim/edit.html.erb
  app/views/nsm/steps/work_item/edit.html.erb
  app/views/prior_authority/steps/case_detail/edit.html.erb
  app/views/prior_authority/steps/client_detail/edit.html.erb
  app/views/prior_authority/steps/hearing_detail/edit.html.erb
  app/views/prior_authority/steps/next_hearing/edit.html.erb
  gems/laa_multi_step_forms/.rubocop.yml
  gems/laa_multi_step_forms/app/attributes/type/multiparam_date.rb
  gems/laa_multi_step_forms/app/helpers/laa_multi_step_forms/form_builder_helper.rb
  gems/laa_multi_step_forms/app/lib/govuk_design_system_formbuilder/elements/fully_validatable_date.rb
  gems/laa_multi_step_forms/docs/Validations.md
  gems/laa_multi_step_forms/spec/attributes/type/multiparam_date_spec.rb
  gems/laa_multi_step_forms/spec/lib/govuk_design_system_formbuilder/builder/fully_validatable_date_spec.rb
  spec/system/prior_authority/client_detail_spec.rb
Labels: approved

#697 CRM457-1303: Mark persist as having succeeded
  app/forms/nsm/steps/solicitor_declaration_form.rb
Labels: approved

#702 CRM457-1281 - Fix bug caused by random data
  spec/services/submit_to_app_store/nsm_payload_builder_spec.rb
Labels: approved

#703 CRM457-1327: Sub/Pub instead of cron
  app/controllers/sync_controller.rb
  app/jobs/pull_updates.rb
  app/services/app_store_client.rb
  app/services/app_store_subscriber.rb
  app/services/app_store_token_authenticator.rb
  app/services/app_store_update_processor.rb
  app/services/prior_authority/assessment_syncer.rb
  config/application.rb
  config/routes.rb
  config/schedule.yml
  spec/jobs/pull_updates_spec.rb
  spec/requests/sync_spec.rb
  spec/services/app_store_subscriber_spec.rb
  spec/services/app_store_update_processor_spec.rb
Labels: approved

#707 CRM457-1327: Allow bypassing sync authentication to enable e2e tests
  app/services/app_store_client.rb
  app/services/app_store_token_authenticator.rb
  config/environments/development.rb
  config/puma.rb
  spec/requests/sync_spec.rb
  spec/services/app_store_client_spec.rb
Labels: approved

#713 CRM457-1229: VAT calculations
  app/lib/cost_calculator.rb
  spec/lib/cost_calculator_spec.rb
Labels: approved

#716 CRM457-1308: Postal evidence
  app/controllers/nsm/steps/supporting_evidence_controller.rb
  app/forms/nsm/steps/supporting_evidence_form.rb
  app/presenters/nsm/check_answers/evidence_uploads_card.rb
  app/views/nsm/steps/supporting_evidence/_content.html.erb
  app/views/nsm/steps/supporting_evidence/edit.html.erb
  app/views/shared/_multifile_upload.html.erb
  config/feature_flags.yml
  config/locales/en/errors.yml
  config/locales/en/nsm/steps.yml
  spec/forms/nsm/steps/supporting_evidence_form_spec.rb
  spec/presenters/nsm/check_answers/evidence_upload_card_spec.rb
  spec/system/nsm/supporting_evidence_spec.rb
Labels: approved, In QA

#704 Fix References to Old Namespaces and Github Teams
  .circleci/config.yml
  .github/CODEOWNERS
  config/environments/production.rb
  config/environments/test.rb
Labels: approved

#699 CRM457-1172: Add line breaks to multi-line display text
  app/presenters/prior_authority/check_answers/alternative_quotes_card.rb
  app/presenters/prior_authority/check_answers/hearing_detail_card.rb
  app/views/prior_authority/steps/additional_costs/_cost_summary.html.erb
  app/views/prior_authority/steps/alternative_quotes/_quote_summary.html.erb
  app/views/prior_authority/steps/check_answers/_primary_quote_details.html.erb
  app/views/prior_authority/steps/primary_quote_summary/_travel_cost_card.html.erb
  config/locales/en/prior_authority/check_answers.yml
  spec/presenters/prior_authority/check_answers/alternative_quotes_card_spec.rb
  spec/presenters/prior_authority/check_answers/hearing_detail_card_spec.rb
  spec/system/prior_authority/check_your_answers/no_prison_law_spec.rb
Labels: approved, In QA

#720 CRM457-1012: Fix payload structure
  app/forms/prior_authority/steps/check_answers_form.rb
  app/services/submit_to_app_store/prior_authority_payload_builder.rb
  spec/services/submit_to_app_store/prior_authority_payload_builder_spec.rb
Labels: approved, In QA

#718 Add envars needed for local integration
  .env.development
  Procfile.dev
Labels: approved

#728 CRM457-1328: Submission notification emails are retryable
  app/forms/nsm/steps/solicitor_declaration_form.rb
  app/forms/prior_authority/steps/check_answers_form.rb
  app/jobs/send_notification_email.rb
  app/jobs/submit_to_app_store.rb
  app/services/submit_to_app_store.rb
  spec/factories/prior_authority_application.rb
  spec/forms/nsm/steps/solicitor_declaration_form_spec.rb
  spec/forms/prior_authority/steps/check_answers_form_spec.rb
  spec/jobs/send_notification_email_spec.rb
  spec/jobs/submit_to_app_store_spec.rb
  spec/services/submit_to_app_store_spec.rb
  spec/system/nsm/solicitor_declaration_spec.rb
  spec/system/prior_authority/check_your_answers/sent_back_for_correct_info_spec.rb
  spec/system/prior_authority/check_your_answers/submission_spec.rb
Labels: approved

#723 Provider - specify environment for sentry
  config/initializers/sentry.rb
Labels: approved

#730 CRM457-1367: Custom validation error messages on add-another forms
  app/controllers/nsm/steps/defendant_summary_controller.rb
  app/controllers/nsm/steps/disbursements_controller.rb
  app/controllers/nsm/steps/work_items_controller.rb
  app/forms/nsm/steps/defendant_summary_form.rb
  app/forms/nsm/steps/disbursements_form.rb
  app/forms/nsm/steps/work_items_form.rb
  config/locales/en/errors.yml
  config/locales/en/helpers.yml
  gems/laa_multi_step_forms/docs/SharedForms.md
Labels: approved

#731 CRM457-1366: Validate MAAT format
  app/forms/nsm/steps/defendant_details_form.rb
  app/forms/prior_authority/steps/case_detail/defendant_form.rb
  config/locales/en/errors.yml
  spec/controllers/nsm/steps/defendants_add_controller_spec.rb
  spec/factories/defendants.rb
  spec/forms/nsm/steps/defendant_details_form_spec.rb
  spec/forms/prior_authority/steps/case_detail/defendant_form_spec.rb
  spec/forms/prior_authority/steps/case_detail_form_spec.rb
  spec/mailers/nsm/submission_mailer_spec.rb
  spec/services/submit_to_app_store/nsm_payload_builder_spec.rb
  spec/services/submit_to_app_store/prior_authority/event_builder_spec.rb
  spec/services/submit_to_app_store/prior_authority_payload_builder_spec.rb
  spec/system/nsm/defendants_spec.rb
  spec/system/prior_authority/case_detail_spec.rb
  spec/system/support/prior_authority/step_helpers.rb
Labels: approved

#711 CRM457-782: Rework claim cost summary page
  app/forms/nsm/steps/disbursement_cost_form.rb
  app/forms/nsm/steps/letters_calls_form.rb
  app/presenters/nsm/check_answers/disbursement_costs_card.rb
  app/presenters/nsm/check_answers/work_items_card.rb
  app/presenters/nsm/cost_summary/disbursements.rb
  app/presenters/nsm/cost_summary/letters_calls.rb
  app/presenters/nsm/cost_summary/report.rb
  app/presenters/nsm/cost_summary/summary.rb
  app/presenters/nsm/cost_summary/work_items.rb
  app/views/nsm/steps/cost_summary/_summary_table.html.erb
  app/views/nsm/steps/cost_summary/show.html.erb
  config/locales/en/nsm/steps.yml
  config/locales/en/nsm/summary.yml
  lib/test_data/nsm_builder.rb
  lib/test_data/pa_builder.rb
  spec/lib/test_data/nsm_builder_spec.rb
  spec/lib/test_data/pa_builder_spec.rb
  spec/presenters/nsm/cost_summary/disbursements_spec.rb
  spec/presenters/nsm/cost_summary/letters_and_calls_spec.rb
  spec/presenters/nsm/cost_summary/report_spec.rb
  spec/presenters/nsm/cost_summary/work_items_spec.rb
  spec/system/nsm/cost_summary_spec.rb
Labels: approved, In QA

#714 CRM457-1295: NSM CYA new cost summary card and layout tweaks
  app/presenters/nsm/check_answers/base.rb
  app/presenters/nsm/check_answers/claim_type_card.rb
  app/presenters/nsm/check_answers/cost_summary_card.rb
  app/presenters/nsm/check_answers/report.rb
  app/views/nsm/steps/check_answers/show.html.erb
  app/views/nsm/steps/cost_summary/_summary_table.html.erb
  config/locales/en/nsm/check_answers.yml
  spec/presenters/nsm/check_answers/claim_type_card_spec.rb
  spec/presenters/nsm/check_answers/report_spec.rb
  spec/system/nsm/check_answers_spec.rb
Labels: approved, In QA

#734 Crm457 1312/submitted view
  app/controllers/nsm/steps/view_claim_controller.rb
  app/presenters/nsm/check_answers/read_only_report.rb
  app/views/nsm/steps/view_claim/show.html.erb
  config/locales/en/nsm/check_answers.yml
  config/locales/en/nsm/steps.yml
  config/locales/en/nsm/view_claim.yml
  spec/presenters/nsm/check_answers/read_only_report_spec.rb
Labels: approved

#736 Make fewer requests to the app store
  app/controllers/sync_controller.rb
  app/services/app_store_update_processor.rb
  app/services/prior_authority/assessment_syncer.rb
  spec/jobs/pull_updates_spec.rb
  spec/requests/sync_spec.rb
  spec/services/app_store_client_spec.rb
  spec/services/app_store_update_processor_spec.rb
  spec/services/prior_authority/assessment_syncer_spec.rb
Labels: approved

#725 CRM457-1373: NSM office codes
  app/controllers/nsm/claims_controller.rb
  app/controllers/nsm/offices_controller.rb
  app/controllers/nsm/steps/office_code_controller.rb
  app/forms/nsm/steps/firm_details/firm_office_form.rb
  app/forms/nsm/steps/office_code_form.rb
  app/models/claim.rb
  app/presenters/nsm/check_answers/your_details_card.rb
  app/presenters/nsm/tasks/firm_details.rb
  app/services/decisions/decision_tree.rb
  app/services/submit_to_app_store/nsm_payload_builder.rb
  app/views/home/index.en.html.erb
  app/views/nsm/claims/index.html.erb
  app/views/nsm/steps/firm_details/edit.html.erb
  app/views/nsm/steps/office_code/edit.html.erb
  config/locales/en/errors.yml
  config/locales/en/helpers.yml
  config/locales/en/nsm/claims.yml
  config/locales/en/nsm/steps.yml
  config/routes.rb
  db/migrate/20240423103901_make_office_code_nullable.rb
  db/schema.rb
  spec/controllers/nsm/claims_controller_spec.rb
  spec/forms/nsm/steps/firm_details/firm_office_form_spec.rb
  spec/presenters/nsm/check_answers/your_details_card_spec.rb
  spec/services/submit_to_app_store/nsm_payload_builder_spec.rb
  spec/system/accessibility_spec.rb
  spec/system/nsm/firm_details_spec.rb
  spec/system/nsm/office_code_spec.rb
  spec/system/sign_in_spec.rb
Labels: approved, In QA

#732 CRM457-750: Add validation to uplift 'Update calculation' buttons
  app/controllers/concerns/add_another_methods.rb
  app/controllers/prior_authority/steps/travel_detail_controller.rb
  app/forms/nsm/steps/letters_calls_form.rb
  app/forms/nsm/steps/work_item_form.rb
  app/views/nsm/steps/letters_calls/edit.html.erb
  app/views/nsm/steps/work_item/edit.html.erb
  config/locales/en/errors.yml
  gems/laa_multi_step_forms/Gemfile.lock
  gems/laa_multi_step_forms/app/controllers/steps/base_step_controller.rb
  gems/laa_multi_step_forms/spec/controllers/steps/base_step_controller_spec.rb
  gems/laa_multi_step_forms/spec/dummy/app/controllers/dummy_step_controller.rb
  spec/forms/nsm/steps/letters_calls_form_spec.rb
  spec/forms/nsm/steps/work_items_add_form_spec.rb
  spec/system/nsm/letters_calls_spec.rb
  spec/system/nsm/work_items_spec.rb
Labels: approved

#741 Stop treating work items as invalid if uplift allowed but not applied
  app/forms/nsm/steps/work_item_form.rb
  spec/forms/nsm/steps/work_items_add_form_spec.rb
Labels: ready for review

#735 CRM457-1370: New office code selection journey for PA
  app/controllers/nsm/claims_controller.rb
  app/controllers/offices_controller.rb
  app/controllers/prior_authority/applications_controller.rb
  app/controllers/prior_authority/offices_controller.rb
  app/controllers/prior_authority/steps/office_code_controller.rb
  app/forms/office_form.rb
  app/forms/prior_authority/steps/case_contact/firm_detail_form.rb
  app/forms/prior_authority/steps/office_code_form.rb
  app/helpers/application_helper.rb
  app/models/claim.rb
  app/models/prior_authority_application.rb
  app/models/provider.rb
  app/presenters/prior_authority/check_answers/case_contact_card.rb
  app/presenters/prior_authority/tasks/case_contact.rb
  app/services/decisions/decision_tree.rb
  app/services/submit_to_app_store/prior_authority/firm_office_payload_builder.rb
  app/views/home/index.html.erb
  app/views/offices/edit.html.erb
  app/views/prior_authority/applications/frame_contents/_draft.html.erb
  app/views/prior_authority/applications/frame_contents/_reviewed.html.erb
  app/views/prior_authority/applications/frame_contents/_submitted.html.erb
  app/views/prior_authority/steps/case_contact/edit.html.erb
  app/views/prior_authority/steps/office_code/edit.html.erb
  config/locales/en/errors.yml
  config/locales/en/offices.yml
  config/locales/en/prior_authority.yml
  config/locales/en/prior_authority/steps.yml
  config/routes.rb
  db/migrate/20240426083917_remove_account_number_from_firm_office.rb
  db/schema.rb
  gems/laa_multi_step_forms/config/locales/errors.yml
  spec/controllers/nsm/claims_controller_spec.rb
  spec/factories/firm_offices.rb
  spec/factories/providers.rb
  spec/forms/prior_authority/steps/case_contact/firm_detail_form_spec.rb
  spec/forms/prior_authority/steps/case_contact_form_spec.rb
  spec/helpers/application_helper_spec.rb
  spec/models/provider_spec.rb
  spec/presenters/prior_authority/check_answers/case_contact_card_spec.rb
  spec/services/submit_to_app_store/prior_authority/event_builder_spec.rb
  spec/services/submit_to_app_store/prior_authority_payload_builder_spec.rb
  spec/support/authentication_helpers.rb
  spec/system/accessibility_spec.rb
  spec/system/prior_authority/application_lists_spec.rb
  spec/system/prior_authority/case_contact_spec.rb
  spec/system/prior_authority/check_your_answers/no_prison_law_spec.rb
  spec/system/prior_authority/create_application_spec.rb
  spec/system/sign_in_spec.rb
  spec/system/support/prior_authority/step_helpers.rb
Labels: approved, In QA
