Repository ministryofjustice/laa-submit-crime-forms, pull requests merged in 2024-05, with the labels that each got.

#745 Add an env var for sending emails
  app/jobs/submit_to_app_store.rb
  helm_deploy/templates/deployment-worker.yaml
  helm_deploy/templates/deployment.yaml
  spec/jobs/submit_to_app_store_spec.rb
Labels: approved

#748 Update app store url
  helm_deploy/values-dev.yaml
Labels: ready for review

#750 6 is the magic number
  helm_deploy/templates/ingress.yaml
Labels: ready for review

#747 CRM457-1300: Content updates
  app/forms/nsm/steps/defendant_details_form.rb
  app/forms/prior_authority/steps/case_detail/defendant_form.rb
  app/forms/prior_authority/steps/case_detail_form.rb
  app/views/prior_authority/steps/additional_costs/edit.html.erb
  app/views/prior_authority/steps/case_detail/edit.html.erb
  app/views/prior_authority/steps/reason_why/edit.html.erb
  config/locales/en/errors.yml
  config/locales/en/prior_authority/steps.yml
  spec/forms/prior_authority/steps/case_detail/defendant_form_spec.rb
Labels: approved, In QA

#751 CRM457-1352: Standardise max file size
  app/javascript/file-upload.js
  app/views/prior_authority/steps/further_information/edit.html.erb
  app/views/prior_authority/steps/reason_why/edit.html.erb
  app/views/shared/_multifile_upload.html.erb
  config/locales/en/prior_authority/steps.yml
Labels: approved

#749 CRM457-970: Add appeal instructions
  app/views/prior_authority/applications/response_summaries/_assessed.html.erb
  config/locales/en/prior_authority.yml
  spec/system/prior_authority/view_applications_spec.rb
Labels: approved, In QA

#752 CRM457-1309: Partial postcodes
  app/forms/prior_authority/steps/alternative_quotes/detail_form.rb
  app/forms/prior_authority/steps/primary_quote_form.rb
  app/presenters/prior_authority/check_answers/primary_quote_card.rb
  app/services/submit_to_app_store/prior_authority/quote_payload_builder.rb
  app/views/prior_authority/steps/primary_quote/edit.html.erb
  app/views/prior_authority/steps/primary_quote_summary/_service_cost_card.html.erb
  config/locales/en/errors.yml
  config/locales/en/prior_authority/alternative_quotes.yml
  config/locales/en/prior_authority/steps.yml
  db/migrate/20240503151919_add_town_to_quotes.rb
  db/migrate/20240507083700_add_fake_towns.rb
  db/schema.rb
  gems/laa_multi_step_forms/app/validators/uk_postcode_validator.rb
  gems/laa_multi_step_forms/spec/validators/uk_postcode_validator_spec.rb
  spec/factories/quote.rb
  spec/forms/prior_authority/steps/primary_quote_form_spec.rb
  spec/presenters/prior_authority/check_answers/primary_quote_card_spec.rb
  spec/services/submit_to_app_store/prior_authority_payload_builder_spec.rb
  spec/system/prior_authority/check_your_answers/no_prison_law_spec.rb
  spec/system/prior_authority/primary_quote_spec.rb
  spec/system/support/prior_authority/step_helpers.rb
Labels: approved, In QA

#755 CRM457-1364 & CRM457-1454
  app/views/nsm/steps/solicitor_declaration/edit.html.erb
  app/views/nsm/steps/supporting_evidence/_content.html.erb
  app/views/nsm/steps/supporting_evidence/_postal_address.html.erb
  app/views/prior_authority/steps/alternative_quote_details/edit.html.erb
  app/views/prior_authority/steps/further_information/edit.html.erb
  app/views/prior_authority/steps/primary_quote/edit.html.erb
  app/views/prior_authority/steps/reason_why/edit.html.erb
  config/locales/en/prior_authority/alternative_quotes.yml
  config/locales/en/prior_authority/steps.yml
Labels: approved

#739 CRM457-1012: Change lister knows about prison law
  app/controllers/prior_authority/steps/further_information_controller.rb
  app/forms/prior_authority/steps/check_answers_form.rb
  app/forms/prior_authority/steps/ufn_form.rb
  app/jobs/submit_to_app_store.rb
  app/presenters/prior_authority/check_answers/compact_further_information_card.rb
  app/presenters/prior_authority/check_answers/report.rb
  app/services/prior_authority/change_lister.rb
  app/views/prior_authority/steps/check_answers/edit.html.erb
  app/views/prior_authority/steps/further_information/edit.html.erb
  config/locales/en/errors.yml
  spec/forms/prior_authority/steps/check_answers_form_spec.rb
  spec/services/submit_to_app_store/prior_authority/event_builder_spec.rb
Labels: approved, In QA

#754 CRM457-1381 & 1431: Amend tasklist inline with designs
  app/assets/stylesheets/custom/task_list.scss
  app/controllers/prior_authority/steps/start_page_controller.rb
  config/locales/en/errors.yml
  config/locales/en/prior_authority.yml
  config/locales/en/tasklist.yml
  gems/laa_multi_step_forms/Gemfile
  gems/laa_multi_step_forms/Gemfile.lock
  gems/laa_multi_step_forms/app/presenters/task_list/collection.rb
  gems/laa_multi_step_forms/app/presenters/task_list/section.rb
  gems/laa_multi_step_forms/app/presenters/task_list/status_tag.rb
  gems/laa_multi_step_forms/app/presenters/task_list/task.rb
  gems/laa_multi_step_forms/app/views/laa_multi_step_forms/task_list/show.html.erb
  gems/laa_multi_step_forms/config/initializers/devise.rb
  gems/laa_multi_step_forms/config/locales/en/tasklist.yml
  gems/laa_multi_step_forms/spec/presenters/task_list/collection_spec.rb
  gems/laa_multi_step_forms/spec/presenters/task_list/section_spec.rb
  gems/laa_multi_step_forms/spec/presenters/task_list/status_tag_spec.rb
  gems/laa_multi_step_forms/spec/presenters/task_list/task_spec.rb
  spec/system/nsm/start_page_spec.rb
  spec/system/prior_authority/additional_costs_spec.rb
  spec/system/prior_authority/alternative_quotes_spec.rb
  spec/system/prior_authority/case_contact_spec.rb
  spec/system/prior_authority/case_detail_spec.rb
  spec/system/prior_authority/client_detail_spec.rb
  spec/system/prior_authority/next_hearing_spec.rb
  spec/system/prior_authority/primary_quote_spec.rb
  spec/system/prior_authority/task_list_spec.rb
  spec/system/prior_authority/youth_court_spec.rb
Labels: approved, In QA

#760 CRM457-1399: Stop wrongly casting to_i
  app/forms/prior_authority/steps/quote_cost_form.rb
  app/validators/item_type_dependant_validator.rb
  spec/forms/prior_authority/steps/alternative_quotes/detail_form_spec.rb
  spec/validators/item_type_dependant_validator_spec.rb
Labels: approved

#759 Crm457 974 - fixes
  app/helpers/tag_helper.rb
  app/presenters/prior_authority/check_answers/base.rb
  app/presenters/prior_authority/check_answers/ufn_card.rb
  app/views/prior_authority/steps/check_answers/_application_details.html.erb
  app/views/prior_authority/steps/check_answers/_primary_quote.html.erb
  app/views/prior_authority/steps/check_answers/edit.html.erb
  config/locales/en/prior_authority.yml
  spec/system/prior_authority/view_applications_spec.rb
Labels: ready for review

#756 Crm457 1458 assessment comments
  app/presenters/nsm/check_answers/application_status_card.rb
  app/services/app_store_update_processor.rb
  app/services/nsm/assessment_syncer.rb
  config/locales/en/nsm/view_claim.yml
  db/migrate/20240507131933_add_assessment_comment_to_claims.rb
  db/schema.rb
  spec/factories/claims.rb
  spec/jobs/pull_updates_spec.rb
  spec/presenters/nsm/check_answers/application_status_card_spec.rb
  spec/services/nsm/assessment_syncer_spec.rb
  spec/services/submit_to_app_store/nsm_payload_builder_spec.rb
  spec/system/accessibility_spec.rb
  spec/system/nsm/view_claim_spec.rb
Labels: ready for review

#766 CRM457-1455: Add horizontal pod autoscaler (HPA) config
  helm_deploy/templates/hpa-worker.yaml
  helm_deploy/templates/hpa.yaml
  helm_deploy/values-dev.yaml
  helm_deploy/values-prod.yaml
  helm_deploy/values-uat.yaml
Labels: ready for review

#762 CRM457-1404: Remove planning expert from list of services
  app/value_objects/prior_authority/quote_services.rb
  config/locales/en/helpers.yml
Labels: approved

#767 CRM457-1437: All radios vertical, with yes before no
  app/views/nsm/steps/office_code/edit.html.erb
  app/views/prior_authority/steps/additional_costs/edit.html.erb
  app/views/prior_authority/steps/alternative_quotes/_no_alternative_quotes.html.erb
  app/views/prior_authority/steps/alternative_quotes/_with_alternative_quotes.html.erb
  app/views/prior_authority/steps/office_code/edit.html.erb
Labels: approved, In QA

#763 CRM457-1387: Cost type is never variable for alternative quotes
  app/forms/prior_authority/steps/alternative_quotes/detail_form.rb
  spec/forms/prior_authority/steps/alternative_quotes/detail_form_spec.rb
  spec/presenters/prior_authority/check_answers/alternative_quotes_card_spec.rb
  spec/system/prior_authority/alternative_quotes_spec.rb
  spec/system/support/prior_authority/step_helpers.rb
Labels: approved, In QA

#770 CRM457-1401: Stop preselecting radio button
  app/forms/nsm/steps/firm_details/solicitor_form.rb
  config/locales/en/errors.yml
  spec/forms/nsm/steps/firm_details/solicitor_form_spec.rb
Labels: approved, In QA

#742 CRM457-1386: improve test users
  .circleci/config.yml
  app/views/home/dev_login.html.erb
  config/gatekeeper.yml
  config/inactive_offices.yml
Labels: approved, In QA

#773 CRM457-1069: Content tweaks for privacy policy
  app/views/about/privacy.en.html.erb
Labels: approved

#771 CRM457-1471: Avoid cookie overflow errors
  Gemfile
  Gemfile.lock
  config/application.rb
  config/environments/production.rb
  config/initializers/sidekiq.rb
  config/locales/en/cookies.yml
Labels: approved

#764 CRM457-1436: "Why PA" update
  app/views/prior_authority/steps/reason_why/edit.html.erb
  config/locales/en/prior_authority/steps.yml
Labels: approved, In QA

#778 Add snyk ignores to codebase
  .circleci/config.yml
  .snyk
Labels: ready for review

#761 CRM457-1432: Validate next hearing date to NOT be in past
  app/forms/prior_authority/steps/hearing_detail_form.rb
  app/forms/prior_authority/steps/next_hearing_form.rb
  config/locales/en/errors.yml
  gems/laa_multi_step_forms/app/forms/steps/base_form_object.rb
  gems/laa_multi_step_forms/spec/forms/steps/base_form_object_spec.rb
  spec/factories/prior_authority_application.rb
  spec/forms/prior_authority/steps/hearing_detail_form_spec.rb
  spec/forms/prior_authority/steps/next_hearing_form_spec.rb
Labels: approved, In QA

#782 CRM457-1449: Start button
  app/views/nsm/claims/index.html.erb
Labels: approved, In QA

#783 CRM457-1450: Back button
  app/controllers/nsm/steps/start_page_controller.rb
  app/controllers/prior_authority/steps/start_page_controller.rb
  gems/laa_multi_step_forms/app/views/laa_multi_step_forms/task_list/show.html.erb
Labels: approved, In QA

#786 CRM457-1429: Add presenter for supporting evidence checkList
  app/presenters/nsm/supporting_evidence/check_list.rb
  app/views/nsm/steps/claim_details/edit.html.erb
  app/views/nsm/steps/supporting_evidence/_content.html.erb
  config/locales/en/helpers.yml
  config/locales/en/nsm/steps.yml
  spec/presenters/nsm/supporting_evidence/check_list_spec.rb
  spec/system/nsm/supporting_evidence_spec.rb
Labels: approved, In QA

#790 switch on portal for dev
  config/feature_flags.yml
Labels: ready for review

#789 Modsec change to allow big data chunck
  helm_deploy/templates/ingress.yaml
Labels: question

#791 Remove portal config for old hosted environment
  config/laa_portal/metadata/dev-crm4.xml
Labels: approved

#793 CRM457-1503: Uplift wrongly applied
  app/forms/nsm/steps/reason_for_claim_form.rb
  spec/forms/nsm/steps/reason_for_claim_form_spec.rb
Labels: approved

#784 CRM457-1450: RBBA Bug Fix
  app/services/risk_assessment/high_risk_assessment.rb
  app/services/risk_assessment/low_risk_assessment.rb
  spec/services/risk_assessment/high_risk_assessment_spec.rb
  spec/services/risk_assessment/low_risk_assessment_spec.rb
  spec/services/risk_assessment/risk_assessment_scorer_spec.rb
Labels: approved

#802 CRM457-1464: Add wasted costs to NSM
  app/forms/nsm/steps/claim_details_form.rb
  app/presenters/nsm/check_answers/claim_details_card.rb
  app/presenters/nsm/supporting_evidence/check_list.rb
  config/locales/en/errors.yml
  config/locales/en/helpers.yml
  config/locales/en/nsm/check_answers.yml
  config/locales/en/nsm/steps.yml
  db/migrate/20240517122619_add_wasted_costs_to_claims.rb
  db/schema.rb
  spec/factories/claims.rb
  spec/forms/nsm/steps/claim_details_form_spec.rb
  spec/presenters/nsm/check_answers/claim_details_card_spec.rb
  spec/presenters/nsm/supporting_evidence/check_list_spec.rb
  spec/services/submit_to_app_store/nsm_payload_builder_spec.rb
  spec/system/nsm/claim_details_spec.rb
  spec/system/nsm/supporting_evidence_spec.rb
Labels: ready for review

#804 crm457-1464: Amend wasted costs presence error message
  config/locales/en/errors.yml
Labels: approved

#806 Increase Dev HPA limits
  helm_deploy/values-dev.yaml
  helm_deploy/values-uat.yaml
Labels: approved

#810 CRM457-1067: Reduce rounding error issues
  app/forms/nsm/steps/disbursement_cost_form.rb
  app/forms/nsm/steps/letters_calls_form.rb
  app/forms/nsm/steps/work_item_form.rb
  app/lib/pricing.rb
  app/models/claim.rb
  app/services/submit_to_app_store/nsm_payload_builder.rb
  spec/presenters/nsm/cost_summary/summary_spec.rb
Labels: ready for review

#805 CRM457-1464: Backfill wasted costs to be 'no'
  db/migrate/20240517152519_update_wasted_costs_on_claims.rb
  db/schema.rb
Labels: approved

#814 Add mileage to disbursement content
  config/locales/en/helpers.yml
  config/locales/en/nsm/summary.yml
  spec/models/disbursement_spec.rb
  spec/system/nsm/cost_summary_spec.rb
  spec/system/nsm/view_claim_spec.rb
Labels: approved

#815 Crm457 1321 - Update source of courts for NSM dropdown and add codes
  Gemfile
  Gemfile.lock
  app/forms/nsm/steps/hearing_details_form.rb
  gems/laa_multi_step_forms/Gemfile
  gems/laa_multi_step_forms/app/models/laa_multi_step_forms/court.rb
  gems/laa_multi_step_forms/config/courts.csv
  gems/laa_multi_step_forms/docs/Setup.md
  gems/laa_multi_step_forms/laa_multi_step_forms.gemspec
  gems/laa_multi_step_forms/spec/models/court_spec.rb
  spec/forms/nsm/steps/hearing_details_form_spec.rb
  spec/system/nsm/hearing_details/suggestion_autocomplete_spec.rb
  spec/system/nsm/hearing_details_spec.rb
Labels: approved

#817 CRM457-1522: Fix pagination breaking aggregation
  app/views/nsm/steps/view_claim/work_items.html.erb
  spec/system/nsm/view_claim_spec.rb
Labels: ready for review

#781 CRM457-1441: New design for incomplete defendants on summary screen
  app/controllers/nsm/steps/defendant_summary_controller.rb
  app/forms/nsm/steps/defendant_details_form.rb
  app/forms/nsm/steps/defendant_summary_form.rb
  app/presenters/nsm/tasks/defendants.rb
  app/views/nsm/steps/defendant_summary/edit.html.erb
  config/locales/en/errors.yml
  spec/factories/defendants.rb
  spec/forms/nsm/steps/defendant_details_form_spec.rb
  spec/forms/nsm/steps/defendant_summary_form_spec.rb
Labels: approved, In QA

#801 CRM457-1424: Add sorting to your claims page
  app/controllers/nsm/claims_controller.rb
  app/views/nsm/claims/index.html.erb
  config/locales/en/nsm/claims.yml
  spec/factories/claims.rb
  spec/factories/defendants.rb
  spec/system/nsm/claims_list_spec.rb
Labels: approved, In QA

#820 CRM457-1491: Fix wording mismatch
  config/locales/en/errors.yml
Labels: approved, In QA

#825 CRM457-1493: Incomplete disbursements
  app/forms/nsm/steps/disbursement_cost_form.rb
  app/forms/nsm/steps/disbursements_form.rb
  app/models/concerns/disbursement_costs.rb
  app/models/disbursement.rb
  app/value_objects/other_disbursement_types.rb
  app/views/nsm/steps/disbursements/edit.html.erb
  config/environments/test.rb
  config/locales/en/errors.yml
  config/locales/en/nsm/steps.yml
  spec/factories/prior_authority_application.rb
  spec/forms/nsm/steps/disbursements_type_form_spec.rb
  spec/system/nsm/disbursements_spec.rb
  spec/system/nsm/work_items_spec.rb
  spec/system/prior_authority/check_your_answers/no_prison_law_spec.rb
Labels: approved

#824 bump braces 3.0.3
  .snyk
  package.json
  yarn.lock
Labels: approved

#828 CRM457-1495: Add content for not enrolled page
  config/locales/en/errors.yml
  gems/laa_multi_step_forms/app/views/laa_multi_step_forms/errors/not_enrolled.html.erb
Labels: ready for review

#827 Crm457 1459/adjustments calculations 3
  app/controllers/nsm/steps/view_claim_controller.rb
  app/models/concerns/letters_and_calls_costs.rb
  app/views/nsm/steps/view_claim/_adjustments.html.erb
  app/views/nsm/steps/view_claim/allowed_letters_and_calls.html.erb
  app/views/nsm/steps/view_claim/disbursements.html.erb
  app/views/nsm/steps/view_claim/show.html.erb
  config/locales/en/nsm/view_claim.yml
  spec/factories/claims.rb
  spec/system/nsm/view_claim_spec.rb
Labels: approved

#826 CRM457-1492: Incomplete work item messaging
  app/components/summary_error_component.html.erb
  app/components/summary_error_component.rb
  app/forms/nsm/steps/work_items_form.rb
  app/views/nsm/steps/work_item_delete/edit.html.erb
  app/views/nsm/steps/work_items/edit.html.erb
  config/locales/en/errors.yml
  config/locales/en/nsm/steps.yml
  spec/components/summary_error_component_spec.rb
  spec/system/nsm/work_items_spec.rb
Labels: approved, In QA

#833 Correctly display status card for part granted applications
  app/models/concerns/letters_and_calls_costs.rb
  app/presenters/nsm/check_answers/application_status_card.rb
  app/presenters/nsm/cost_summary/summary.rb
  spec/factories/claims.rb
  spec/presenters/nsm/check_answers/application_status_card_spec.rb
Labels: approved

#835 Disable mock portal auth in UAT
  config/feature_flags.yml
Labels: ready for review

#838 Crm457 1459/adjustments calculations 7
  app/lib/number_to.rb
  app/views/nsm/steps/view_claim/disbursement.html.erb
  config/locales/en/nsm/view_claim.yml
  spec/factories/disbursements.rb
  spec/presenters/nsm/check_answers/application_status_card_spec.rb
  spec/system/nsm/view_claim_spec.rb
Labels: approved

#845 CRM457-1542: Amend appeal content for part-granted/rejected applications
  config/locales/en/prior_authority.yml
Labels: ready for review

#849 Crm457 1541/missing travel reason
  app/forms/prior_authority/steps/case_detail_form.rb
  app/forms/prior_authority/steps/travel_detail_form.rb
  app/presenters/prior_authority/tasks/primary_quote.rb
  spec/factories/quote.rb
  spec/presenters/prior_authority/tasks/primary_quote_spec.rb
  spec/services/submit_to_app_store/prior_authority_payload_builder_spec.rb
Labels: approved
