Repository ministryofjustice/laa-submit-crime-forms, pull requests merged in 2024-10, with the labels that each got.

#1213 CRM457-2096: Validate data before submission
  Gemfile
  Gemfile.lock
  app/services/submit_to_app_store/prior_authority_payload_builder.rb
  lib/tasks/submit_dummy_data.rake
  lib/test_data/pa_resubmitter.rb
  spec/factories/firm_offices.rb
  spec/factories/prior_authority_application.rb
  spec/factories/solicitors.rb
  spec/lib/test_data/pa_resubmitter_spec.rb
  spec/services/submit_to_app_store/prior_authority_payload_builder_spec.rb
Labels: approved

#1215 Bump gem version
  Gemfile
  Gemfile.lock
Labels: ready for review

#1216 CRM457-2129: Use NSM schema validation
  Gemfile
  Gemfile.lock
  app/services/submit_to_app_store/nsm_payload_builder.rb
  spec/factories/claims.rb
  spec/factories/work_items.rb
  spec/services/submit_to_app_store/nsm_payload_builder_spec.rb
Labels: approved, In QA

#1220 Bump gem
  Gemfile
  Gemfile.lock
Labels: ready for review

#1221 CRM457-2007: Provider search mechanism
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/custom/search.scss
  app/controllers/nsm/claims_controller.rb
  app/controllers/prior_authority/applications_controller.rb
  app/forms/search_form.rb
  app/helpers/sortable_table_helper.rb
  app/services/search_service.rb
  app/services/submit_to_app_store/nsm_payload_builder.rb
  app/views/nsm/claims/search.html.erb
  app/views/prior_authority/applications/_generic_table.html.erb
  app/views/prior_authority/applications/_reviewed.html.erb
  app/views/prior_authority/applications/search.html.erb
  config/locales/en/nsm/search.yml
  config/locales/en/prior_authority.yml
  config/locales/en/prior_authority/search.yml
  config/routes.rb
  db/migrate/20241007161008_add_search_fields.rb
  db/schema.rb
  spec/system/search_spec.rb
Labels: approved

#1222 Bump gem
  Gemfile
  Gemfile.lock
Labels: approved

#1226 CRM457-1988 (BUG): Fix expired claim logic
  app/presenters/nsm/check_answers/application_status_card.rb
Labels: ready for review

#1214 CRM457-2126: Fix high risk calculation
  app/services/risk_assessment/high_risk_assessment.rb
  spec/factories/work_items.rb
  spec/services/risk_assessment/high_risk_assessment_spec.rb
  spec/services/risk_assessment/risk_assessment_scorer_spec.rb
Labels: approved, In QA

#1227 CRM457-1988: Moar fixes
  Gemfile
  Gemfile.lock
  app/presenters/nsm/check_answers/application_status_card.rb
Labels: ready for review

#1225 CRM457-2144: Dynamic page titles
  gems/laa_multi_step_forms/.rubocop.yml
  gems/laa_multi_step_forms/app/helpers/laa_multi_step_forms/application_helper.rb
  gems/laa_multi_step_forms/spec/dummy/config/locales/en.yml
  gems/laa_multi_step_forms/spec/helpers/application_helper_spec.rb
  gems/laa_multi_step_forms/spec/lib/govuk_design_system_formbuilder/builder/period_spec.rb
Labels: approved, In QA

#1229 CRM457-2058: Fix dev portal integration
  helm_deploy/values-dev.yaml
Labels: approved

#1177 CRM457-1809: Use provider API to check whether office codes are inactive
  .env.development
  .env.test
  Gemfile
  Gemfile.lock
  app/controllers/about/cookies_controller.rb
  app/controllers/about_controller.rb
  app/controllers/application_controller.rb
  app/controllers/errors/inactive_offices_controller.rb
  app/controllers/healthcheck_controller.rb
  app/controllers/home_controller.rb
  app/controllers/nsm/claims_controller.rb
  app/controllers/nsm/offences_controller.rb
  app/controllers/nsm/steps/base_controller.rb
  app/controllers/prior_authority/applications_controller.rb
  app/controllers/prior_authority/steps/base_controller.rb
  app/controllers/providers/omniauth_callbacks_controller.rb
  app/controllers/robots_controller.rb
  app/controllers/sync_controller.rb
  app/forms/nsm/steps/office_code_form.rb
  app/forms/prior_authority/steps/office_code_form.rb
  app/models/provider.rb
  app/services/active_office_code_service.rb
  app/services/providers/gatekeeper.rb
  app/views/home/dev_login.html.erb
  app/views/home/index.html.erb
  config/application.rb
  config/gatekeeper_crm4.yml
  config/gatekeeper_crm5.yml
  config/gatekeeper_crm7.yml
  config/inactive_offices.yml
  config/office_code_overrides.yml
  db/schema.rb
  helm_deploy/templates/deployment-worker.yaml
  helm_deploy/templates/deployment.yaml
  helm_deploy/values-dev.yaml
  helm_deploy/values-prod.yaml
  helm_deploy/values-uat.yaml
  spec/controllers/providers/omniauth_callbacks_controller_spec.rb
  spec/factories/providers.rb
  spec/models/provider_spec.rb
  spec/services/active_office_code_service_spec.rb
  spec/services/providers/gatekeeper_spec.rb
  spec/support/authentication_helpers.rb
  spec/system/access_spec.rb
  spec/system/nsm/office_code_spec.rb
  spec/system/prior_authority/case_contact_spec.rb
  spec/system/sign_in_spec.rb
Labels: approved

#1235 CRM457-2152: Remove false positive
  helm_deploy/templates/ingress.yaml
Labels: approved

#1234 CRM457-2146: Remove duplicate headers
  app/presenters/nsm/check_answers/read_only_report.rb
Labels: approved, In QA

#1232 CRM457-2130: Draft deletion UI
  app/controllers/nsm/claims_controller.rb
  app/controllers/prior_authority/applications_controller.rb
  app/views/nsm/claims/confirm_delete.html.erb
  app/views/nsm/claims/index.html.erb
  app/views/prior_authority/applications/confirm_delete.html.erb
  config/locales/en/nsm/claims.yml
  config/locales/en/prior_authority.yml
  gems/laa_multi_step_forms/app/views/layouts/govuk_template.html.erb
  spec/system/nsm/delete_claim_spec.rb
Labels: approved, In QA

#1233 CRM457-2142: Tweak additional cost deletion flow
  app/controllers/prior_authority/steps/additional_cost_details_controller.rb
  app/views/prior_authority/steps/additional_cost_details/confirm_delete.html.erb
  config/locales/en/prior_authority/steps.yml
  spec/system/prior_authority/additional_costs_spec.rb
Labels: approved, In QA

#1230 CRM457-1988: NSM RFI QA feedback
  app/controllers/nsm/steps/solicitor_declaration_controller.rb
  app/presenters/nsm/check_answers/application_status_card.rb
  app/views/nsm/steps/further_information/edit.html.erb
  app/views/prior_authority/steps/further_information/edit.html.erb
  config/locales/en/nsm/steps.yml
  config/locales/en/nsm/view_claim.yml
  config/locales/en/prior_authority/steps.yml
  spec/presenters/nsm/check_answers/application_status_card_spec.rb
  spec/system/prior_authority/check_your_answers/sent_back_for_further_info_spec.rb
  spec/system/prior_authority/further_information_request_spec.rb
Labels: approved, In QA

#1231 CRM457-2101: Move clam to separate deployment/pods
  bin/deploy
  config/clamd/clamd.cloud-platform.conf
  config/clamd/clamd.dev.conf
  config/clamd/clamd.prod.conf
  config/clamd/clamd.uat.conf
  helm_deploy/templates/custom-error-pages.yaml
  helm_deploy/templates/deployment-clamav.yaml
  helm_deploy/templates/deployment-custom-errors.yaml
  helm_deploy/templates/deployment-worker.yaml
  helm_deploy/templates/deployment.yaml
  helm_deploy/templates/service.yaml
  helm_deploy/values-dev.yaml
  helm_deploy/values-prod.yaml
  helm_deploy/values-uat.yaml
Labels: approved

#1236 CRM457-2064: Get office codes from provider data API
  app/controllers/providers/omniauth_callbacks_controller.rb
  app/models/provider.rb
  app/services/active_office_code_service.rb
  app/services/office_code_service.rb
  app/services/provider_data_api_client.rb
  spec/controllers/providers/omniauth_callbacks_controller_spec.rb
  spec/models/provider_spec.rb
  spec/services/active_office_code_service_spec.rb
  spec/services/office_code_service_spec.rb
  spec/support/authentication_helpers.rb
Labels: approved

#1240 CRM457-2095: Add flags indicating sync job status
  app/jobs/send_notification_email.rb
  app/jobs/submit_to_app_store.rb
  app/services/submit_to_app_store/nsm_payload_builder.rb
  db/migrate/20241015084055_add_synced_to_app_store_to_submissions.rb
  db/schema.rb
  spec/jobs/send_notification_email_spec.rb
  spec/jobs/submit_to_app_store_spec.rb
  spec/rails_helper.rb
Labels: approved

#1241 CRM457-2013: Stop orphaning solicitor records
  app/forms/prior_authority/steps/case_contact/solicitor_form.rb
  app/forms/prior_authority/steps/case_contact_form.rb
  app/models/claim.rb
  app/models/firm_office.rb
  app/models/prior_authority_application.rb
  app/models/solicitor.rb
  db/migrate/20241015133053_delete_orphans.rb
  db/schema.rb
Labels: approved

#1239 CRM457-2089: New add a work item flow
  app/controllers/nsm/steps/work_item_controller.rb
  app/controllers/nsm/steps/work_items_controller.rb
  app/forms/nsm/steps/work_item_form.rb
  app/forms/nsm/steps/work_items_form.rb
  app/models/work_item.rb
  app/presenters/nsm/cost_summary/base.rb
  app/presenters/nsm/cost_summary/disbursements.rb
  app/presenters/nsm/cost_summary/report.rb
  app/presenters/nsm/cost_summary/work_items.rb
  app/presenters/nsm/tasks/work_items.rb
  app/presenters/nsm/work_items_row.rb
  app/services/decisions/decision_tree.rb
  app/views/nsm/steps/work_item/edit.html.erb
  app/views/nsm/steps/work_items/edit.html.erb
  config/locales/en/errors.yml
  config/locales/en/helpers.yml
  config/locales/en/nsm/steps.yml
  config/locales/en/nsm/steps/work_items.yml
  config/locales/en/nsm/summary.yml
  config/routes.rb
  spec/controllers/nsm/steps/work_items_add_controller_spec.rb
  spec/decisions/decision_tree_spec.rb
  spec/forms/nsm/steps/work_items_add_form_spec.rb
  spec/presenter/nsm/steps/work_items_presenter_spec.rb
  spec/presenters/nsm/cost_summary/report_spec.rb
  spec/presenters/nsm/work_items_row_spec.rb
  spec/support/steps/a_generic_step_controller.rb
  spec/system/accessibility_spec.rb
  spec/system/nsm/work_items_spec.rb
Labels: approved, In QA

#1253 CRM457-2169: Update email validation to match Notify
  app/forms/nsm/steps/contact_details_form.rb
  app/forms/prior_authority/steps/case_contact/solicitor_form.rb
  app/lib/regular_expressions.rb
  app/validators/email_format_validator.rb
  spec/validators/email_format_validator_spec.rb
Labels: approved

#1256 CRM457-2178 Marks office codes to active
  config/office_code_overrides.yml
Labels: approved

#1254 CRM457-2173: Fix "back" and "change" buttons in PA RFI
  app/helpers/decision_step_header_helper.rb
  app/presenters/prior_authority/check_answers/base.rb
  app/presenters/prior_authority/check_answers/further_information_card.rb
  app/presenters/prior_authority/check_answers/ufn_card.rb
  app/services/decisions/back_decision_tree.rb
  app/services/decisions/decision_tree.rb
  spec/system/prior_authority/further_information_request_spec.rb
Labels: approved, In QA

#1188 CRM7 Provider: Amend main/additional defendant content
  app/forms/nsm/steps/defendant_details_form.rb
  app/forms/nsm/steps/defendant_summary_form.rb
  app/presenters/nsm/check_answers/defendant_card.rb
  app/views/nsm/steps/defendant_delete/edit.html.erb
  app/views/nsm/steps/defendant_details/edit.html.erb
  app/views/nsm/steps/defendant_summary/edit.html.erb
  config/locales/en/nsm/check_answers.yml
  config/locales/en/nsm/steps.yml
  gems/laa_multi_step_forms/app/helpers/laa_multi_step_forms/check_missing_helper.rb
  spec/presenters/nsm/check_answers/defendant_card_spec.rb
  spec/system/nsm/defendants_spec.rb
Labels: approved, In QA

#1255 CRM457-2106: NSM search
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/custom/search.scss
  app/controllers/concerns/searchable.rb
  app/controllers/nsm/claims_controller.rb
  app/controllers/prior_authority/applications_controller.rb
  app/forms/search_form.rb
  app/javascript/application.js
  app/javascript/date-picker.js
  app/javascript/handle-forms.js
  app/jobs/submit_to_app_store.rb
  app/services/search_service.rb
  app/services/submit_to_app_store/nsm_payload_builder.rb
  app/views/layouts/nsm.html.erb
  app/views/layouts/nsm/_primary_navigation.html.erb
  app/views/nsm/claims/search.html.erb
  config/locales/en/errors.yml
  config/locales/en/nsm.yml
  config/locales/en/nsm/search.yml
  db/migrate/20241017140210_add_originally_submitted_at_to_submissions.rb
  db/schema.rb
  gems/laa_multi_step_forms/app/views/layouts/govuk_template.html.erb
  spec/jobs/submit_to_app_store_spec.rb
  spec/system/search_spec.rb
Labels: approved, In QA

#1258 CRM457-2106: Backfill timestamps
  db/migrate/20241021092835_backfill_originally_submitted_at.rb
  db/migrate/20241021_nsm_originally_submitted.csv
  db/migrate/20241021_pa_originally_submitted.csv
  db/schema.rb
Labels: approved

#1259 CRM457-2098: Add PII annotations
  db/pii.yml
  spec/models/pii_spec.rb
Labels: approved

#1251 CRM457-2162: Tweak task list behaviour
  app/presenters/nsm/tasks/base.rb
  app/presenters/nsm/tasks/cost_summary.rb
  app/presenters/nsm/tasks/defendants.rb
  app/presenters/nsm/tasks/disbursements.rb
  app/presenters/nsm/tasks/work_items.rb
  app/views/nsm/claims/search.html.erb
  config/initializers/time_formats.rb
  spec/presenter/nsm/steps/cost_summary_presenter_spec.rb
  spec/presenter/nsm/steps/solicitor_declaration_presenter_spec.rb
  spec/system/nsm/task_list_spec.rb
Labels: approved, In QA

#1257 CRM457-2005: Tweak PA RFI UI
  app/presenters/prior_authority/check_answers/report.rb
  app/views/prior_authority/applications/_application_details.html.erb
  app/views/prior_authority/applications/response_summaries/_expired.html.erb
  app/views/prior_authority/steps/check_answers/edit.html.erb
  config/locales/en/prior_authority.yml
  config/locales/en/prior_authority/check_answers.yml
  spec/presenters/prior_authority/check_answers/report_spec.rb
Labels: approved, In QA

#1267 CRM457-2187: Fix file deletion via check answers screen
  app/javascript/file-upload.js
Labels: approved

#1263 CRM457-2174: Only allow access to appropriate steps
  app/controllers/nsm/steps/base_controller.rb
  app/controllers/nsm/steps/claim_confirmation_controller.rb
  app/controllers/nsm/steps/further_information_controller.rb
  app/controllers/nsm/steps/solicitor_declaration_controller.rb
  app/controllers/nsm/steps/start_page_controller.rb
  app/controllers/nsm/steps/view_claim_controller.rb
  app/controllers/prior_authority/steps/base_controller.rb
  app/controllers/prior_authority/steps/check_answers_controller.rb
  app/controllers/prior_authority/steps/further_information_controller.rb
  app/controllers/prior_authority/steps/start_page_controller.rb
  app/controllers/prior_authority/steps/submission_confirmation_controller.rb
  app/presenters/prior_authority/start_page.rb
  app/views/prior_authority/steps/next_hearing/edit.html.erb
  spec/controllers/nsm/steps/claim_confirmation_controller_spec.rb
  spec/controllers/nsm/steps/defendants_delete_controller_spec.rb
  spec/controllers/nsm/steps/disbursements_delete_controller_spec.rb
  spec/controllers/nsm/steps/view_claim_controller_spec.rb
  spec/controllers/nsm/steps/work_items_delete_controller_spec.rb
  spec/controllers/prior_authority/check_answers_controller_spec.rb
  spec/controllers/prior_authority/start_page_controller_spec.rb
  spec/system/nsm/disbursements_spec.rb
  spec/system/nsm/further_information_spec.rb
  spec/system/nsm/view_claim/disbursement_spec.rb
  spec/system/nsm/view_claim_spec.rb
  spec/system/prior_authority/check_your_answers/submission_spec.rb
  spec/system/prior_authority/corrections_spec.rb
Labels: approved, In QA

#1266 Updates statement
  app/views/about/accessibility.en.html.erb
Labels: approved

#1268 CRM457-2191: Prevent incomplete submissions
  app/controllers/nsm/steps/solicitor_declaration_controller.rb
  app/presenters/nsm/tasks/disbursements.rb
  spec/controllers/nsm/steps/solicitor_declaration_controller_spec.rb
  spec/presenter/nsm/steps/disbursements_presenter_spec.rb
  spec/system/nsm/further_information_spec.rb
  spec/system/nsm/solicitor_declaration_spec.rb
Labels: approved, In QA

#1271 CRM457-2168: Clamby not updating
  .github/actions/run-freshclam/action.yml
  .github/workflows/update-virus-definitions.yml
  app/jobs/update_virus_definitions.rb
  config/schedule.yml
  spec/jobs/update_virus_definitions_spec.rb
Labels: approved

#1274 CRM457-2168: Fix ClamAV update run
  .github/workflows/update-virus-definitions.yml
Labels: approved

#1228 CRM457-2122: Improve autocomplete effectiveness
  app/controllers/prior_authority/steps/primary_quote_controller.rb
  app/javascript/application.js
  app/javascript/autocomplete.js
  app/views/prior_authority/steps/primary_quote/edit.html.erb
  package.json
  yarn.lock
Labels: approved, In QA

#1281 CRM457-2168: Use correct secrets
  .github/workflows/update-virus-definitions.yml
Labels: approved

#1261 CRM457-2099: Improve disbursement flows
  app/controllers/nsm/steps/disbursement_cost_controller.rb
  app/controllers/nsm/steps/disbursements_controller.rb
  app/forms/nsm/steps/disbursement_cost_form.rb
  app/forms/nsm/steps/disbursements_form.rb
  app/models/disbursement.rb
  app/presenters/nsm/cost_summary/disbursements.rb
  app/presenters/nsm/tasks/disbursements.rb
  app/services/decisions/decision_tree.rb
  app/views/nsm/steps/disbursement_cost/edit.html.erb
  app/views/nsm/steps/disbursement_delete/edit.html.erb
  app/views/nsm/steps/disbursements/edit.html.erb
  config/locales/en/errors.yml
  config/locales/en/helpers.yml
  config/locales/en/nsm/steps.yml
  config/locales/en/nsm/summary.yml
  spec/decisions/decision_tree_spec.rb
  spec/forms/nsm/steps/disbursements_cost_form_spec.rb
  spec/presenter/nsm/steps/disbursements_presenter_spec.rb
  spec/presenters/nsm/check_answers/disbursement_cost_card_spec.rb
  spec/presenters/nsm/cost_summary/disbursements_spec.rb
  spec/system/nsm/cost_summary_spec.rb
  spec/system/nsm/disbursement_type/disbursement_costs_spec.rb
  spec/system/nsm/disbursements_spec.rb
Labels: approved, In QA
