Repository ministryofjustice/laa-submit-crime-forms, pull requests merged in 2024-06, with the labels that each got.

#853 Crm457 1568/failed update
  app/forms/prior_authority/steps/check_answers_form.rb
  app/services/app_store_client.rb
  spec/services/app_store_client_spec.rb
Labels: approved

#858 CRM457-1514: Onboard first Prior authority (CRM4) tranche
  config/gatekeeper.yml
Labels: approved

#830 CRM457-1493: Remove validation exception
  app/forms/nsm/steps/disbursement_cost_form.rb
  app/models/concerns/disbursement_costs.rb
  app/models/disbursement.rb
  config/locales/en/errors.yml
  spec/factories/disbursements.rb
  spec/system/nsm/disbursements_spec.rb
Labels: approved, In QA

#870 Fix Alternative Quotes Incorrect Data
  app/services/submit_to_app_store/prior_authority/quote_payload_builder.rb
  spec/factories/prior_authority_application.rb
Labels: approved

#873 CRM457-1559: Appeal info
  app/presenters/nsm/check_answers/application_status_card.rb
  app/views/nsm/steps/view_claim/_appeal.html.erb
  config/locales/en/nsm/check_answers.yml
  config/locales/en/nsm/view_claim.yml
  spec/presenters/nsm/check_answers/application_status_card_spec.rb
Labels: approved, In QA

#876 CRM457-1590: Enable simple onboarding of ALL providers per service
  app/services/providers/gatekeeper.rb
  spec/services/providers/gatekeeper_spec.rb
  spec/system/access_spec.rb
  spec/system/sign_in_spec.rb
Labels: ready for review

#877 CRM457-1562: Allow for multi line text on assessment comment
  app/views/prior_authority/applications/response_summaries/_assessed.html.erb
  app/views/prior_authority/steps/check_answers/_primary_quote_details.html.erb
Labels: approved

#878 CRM457-1592: Separate gatekeeper config per service
  app/services/providers/gatekeeper.rb
  config/application.rb
  config/gatekeeper.yml
  config/gatekeeper_crm4.yml
  config/gatekeeper_crm5.yml
  config/gatekeeper_crm7.yml
  spec/services/providers/gatekeeper_spec.rb
  spec/system/access_spec.rb
  spec/system/sign_in_spec.rb
Labels: ready for review

#880 CRM457-1592: Separate gatekeeper config per service
  app/services/providers/gatekeeper.rb
  config/application.rb
  config/gatekeeper.yml
  config/gatekeeper_crm4.yml
  config/gatekeeper_crm5.yml
  config/gatekeeper_crm7.yml
  spec/services/providers/gatekeeper_spec.rb
  spec/system/access_spec.rb
  spec/system/sign_in_spec.rb
Labels: ready for review

#882 CMR457-1594: Fix GDS error handling on remittal date field
  app/views/nsm/steps/case_details/edit.html.erb
Labels: ready for review

#881 CRM457-1515: Add second CRM4 onboarding tranche - 11/06/2024
  config/gatekeeper_crm4.yml
Labels: DO NOT MERGE, approved, ready for review

#885 crm457-1594: Add custom date errors for main offence and remittal
  config/locales/en/errors.yml
Labels: approved, ready for review

#883 CRM457-1599: Make CRM7's prior authority question conditional
  app/forms/nsm/steps/disbursement_cost_form.rb
  app/forms/nsm/steps/disbursement_type_form.rb
  app/models/disbursement.rb
  app/views/nsm/steps/disbursement_cost/edit.html.erb
  app/views/nsm/steps/disbursements/edit.html.erb
  spec/forms/nsm/steps/disbursements_cost_form_spec.rb
  spec/forms/nsm/steps/disbursements_type_form_spec.rb
  spec/system/nsm/disbursement_type/disbursement_costs_spec.rb
  spec/system/nsm/disbursements_spec.rb
Labels: approved, In QA

#840 Crm457 1459/adjustments calculations 8
  app/models/concerns/disbursement_costs.rb
  app/models/concerns/letters_and_calls_costs.rb
  app/presenters/nsm/check_answers/cost_summary_card.rb
  app/presenters/nsm/check_answers/read_only_report.rb
  app/presenters/nsm/cost_summary/summary.rb
  app/views/nsm/steps/check_answers/show.html.erb
  app/views/nsm/steps/view_claim/_adjustments.html.erb
  app/views/nsm/steps/view_claim/_cost_summary.html.erb
  app/views/nsm/steps/view_claim/allowed_disbursements.html.erb
  app/views/nsm/steps/view_claim/allowed_letters_and_calls.html.erb
  app/views/nsm/steps/view_claim/allowed_work_items.html.erb
  app/views/nsm/steps/view_claim/calls.html.erb
  app/views/nsm/steps/view_claim/disbursement.html.erb
  app/views/nsm/steps/view_claim/disbursements.html.erb
  app/views/nsm/steps/view_claim/letters.html.erb
  app/views/nsm/steps/view_claim/work_item.html.erb
  app/views/nsm/steps/view_claim/work_items.html.erb
  app/views/shared/_pagination.html.erb
  config/locales/en/nsm/check_answers.yml
  config/locales/en/nsm/view_claim.yml
  spec/factories/disbursements.rb
  spec/presenters/nsm/check_answers/application_status_card_spec.rb
  spec/presenters/nsm/check_answers/cost_summary_card_spec.rb
  spec/system/nsm/check_answers_spec.rb
  spec/system/nsm/view_claim_spec.rb
Labels: approved

#874 CRM457-1526: Risk calculation
  app/services/risk_assessment/high_risk_assessment.rb
  spec/services/risk_assessment/high_risk_assessment_spec.rb
Labels: approved, In QA

#895 CRM457-1608: Change date hints to more recent date
  config/locales/en/helpers.yml
  config/locales/en/prior_authority/steps.yml
Labels: approved, In QA

#892 CRM457-1457: Export metrics to prometheus
  Gemfile
  Gemfile.lock
  config.ru
  config/initializers/prometheus.rb
  helm_deploy/templates/deployment.yaml
  helm_deploy/templates/service.yaml
Labels: approved

#894 CRM457-1600: Supporting evidence delete button fix
  app/controllers/prior_authority/steps/further_information_controller.rb
  app/controllers/prior_authority/steps/reason_why_controller.rb
  app/javascript/file-upload.js
  app/views/nsm/steps/supporting_evidence/edit.html.erb
  app/views/prior_authority/steps/further_information/edit.html.erb
  app/views/shared/_multifile_upload.html.erb
  spec/factories/further_informations.rb
  spec/presenters/prior_authority/check_answers/further_information_card_spec.rb
  spec/services/submit_to_app_store/prior_authority_payload_builder_spec.rb
  spec/system/nsm/supporting_evidence_spec.rb
  spec/system/prior_authority/further_information_request_spec.rb
  spec/system/prior_authority/reason_why_spec.rb
  spec/system/support/screenshot_helper.rb
Labels: approved, In QA

#907 CRM457-1618: Send to correct email
  app/mailers/nsm/submission_mailer.rb
  spec/mailers/nsm/submission_mailer_spec.rb
Labels: ready for review

#908 CRM457-1580: Fix case
  config/locales/en/nsm/steps.yml
Labels: ready for review

#904 CRM457-1617: Add progress bar and check mark to denote successful upload
  app/javascript/file-upload.js
  app/views/shared/_multifile_upload.html.erb
  spec/system/nsm/supporting_evidence_spec.rb
  spec/system/prior_authority/further_information_request_spec.rb
  spec/system/prior_authority/reason_why_spec.rb
Labels: approved, In QA

#912 End to End Test Required to Pass Before any Deployment
  .circleci/config.yml
Labels: approved

#911 CRM457-1517: Onboard CRM4/PA tranche 3 on 18/06/2024
  config/gatekeeper_crm4.yml
Labels: ready for review

#915 Only migrate allowed_miles and allowed_apply_vat if not exists
  db/migrate/20240614154401_add_missing_fields_to_disbursements.rb
  db/schema.rb
Labels: ready for review

#914 CRM457: Fix bug in deactivated office check
  app/services/providers/active_office_checker.rb
  spec/controllers/providers/omniauth_callbacks_controller_spec.rb
Labels: ready for review

#919 Replace HPA with standard replica and rolling update strategy
  helm_deploy/templates/deployment-worker.yaml
  helm_deploy/templates/deployment.yaml
  helm_deploy/templates/hpa-worker.yaml
  helm_deploy/templates/hpa.yaml
  helm_deploy/values-dev.yaml
  helm_deploy/values-prod.yaml
  helm_deploy/values-uat.yaml
Labels: approved

#925 Separate worker and app pod replica config
  helm_deploy/templates/deployment-worker.yaml
  helm_deploy/templates/deployment.yaml
  helm_deploy/values-dev.yaml
  helm_deploy/values-prod.yaml
  helm_deploy/values-uat.yaml
Labels: approved

#906 CRM457-1408: Custom modsec errors
  bin/deploy
  helm_deploy/templates/custom-error-pages.yaml
  helm_deploy/templates/deployment-custom-errors.yaml
  helm_deploy/templates/ingress.yaml
  helm_deploy/templates/service.yaml
  helm_deploy/values-dev.yaml
  helm_deploy/values-prod.yaml
  helm_deploy/values-uat.yaml
Labels: approved

#921 CRM457-1415: Deactivate and audit office codes
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/providers/omniauth_callbacks_controller.rb
  app/forms/nsm/steps/office_code_form.rb
  app/forms/prior_authority/steps/office_code_form.rb
  app/models/provider.rb
  app/services/auditor.rb
  app/services/providers/active_office_checker.rb
  app/services/providers/gatekeeper.rb
  config/inactive_offices.yml
  config/initializers/table_print.rb
  lib/tasks/audit.rake
  spec/controllers/providers/omniauth_callbacks_controller_spec.rb
  spec/lib/tasks/audit_spec.rb
  spec/models/provider_spec.rb
  spec/services/auditor_spec.rb
  spec/services/providers/gatekeeper_spec.rb
  spec/system/sign_in_spec.rb
Labels: approved, In QA

#929 CRM457-1650: Fix modsec tagging
  helm_deploy/templates/ingress.yaml
Labels: approved

#922 CRM457-1643: Don't try to report nil to Sentry
  app/controllers/concerns/multi_file_uploadable.rb
  app/controllers/nsm/steps/supporting_evidence_controller.rb
  app/controllers/prior_authority/steps/further_information_controller.rb
  app/controllers/prior_authority/steps/reason_why_controller.rb
Labels: approved, In QA

#905 CRM457-1358: Add maintenance mode screen
  app/controllers/application_controller.rb
  config/feature_flags.yml
  config/initializers/content_security_policy.rb
  public/crest.svg
  public/gds-transport-bold.woff2
  public/gds-transport-light.woff2
  public/maintenance.html
  spec/system/maintenance_mode_spec.rb
Labels: approved, In QA

#934 CRM457-1657: Remove some modsec false positives
  helm_deploy/templates/ingress.yaml
Labels: approved

#935 CRM457-1408: Custom Modsec errors attempt 2
  bin/deploy
  helm_deploy/templates/custom-error-pages.yaml
  helm_deploy/templates/deployment-custom-errors.yaml
  helm_deploy/templates/ingress.yaml
  helm_deploy/templates/service.yaml
  helm_deploy/values-dev.yaml
  helm_deploy/values-prod.yaml
  helm_deploy/values-uat.yaml
Labels: approved, In QA

#927 [CRM457-1640] CRM7 invalid date bug (when date field is not required)
  app/forms/nsm/steps/case_details_form.rb
  app/forms/nsm/steps/case_disposal_form.rb
  app/forms/nsm/steps/disbursement_cost_form.rb
  spec/forms/nsm/steps/case_details_form_spec.rb
Labels: approved

#938 Delete redis pvc on merge into main
  .github/actions/delete-dev-release/action.yml
Labels: approved

#939 CRM457-1661: Update contact page content
  app/views/about/contact.en.html.erb
  config/application.rb
Labels: approved, In QA

#940 CRM457-1675: Fix spelling mistake
  app/value_objects/reason_for_claim.rb
  config/locales/en/helpers.yml
  spec/forms/nsm/steps/reason_for_claim_form_spec.rb
  spec/presenters/nsm/check_answers/letters_calls_card_spec.rb
  spec/value_object/nsm/reason_for_claim_spec.rb
Labels: approved, In QA

#941 CRM457-1682 - Provider: Incorrect Client Email Validation
  app/forms/nsm/steps/firm_details/solicitor_form.rb
  app/forms/prior_authority/steps/case_contact/solicitor_form.rb
  spec/forms/nsm/steps/firm_details/solicitor_form_spec.rb
  spec/forms/prior_authority/steps/case_contact/solicitor_form_spec.rb
Labels: approved

#947 CRM457-1666: CRM7 Provider confirmation content change
  app/views/nsm/steps/claim_confirmation/show.html.erb
  config/locales/en/nsm/steps.yml
  gems/laa_multi_step_forms/config/locales/en/helpers.yml
  spec/system/nsm/claim_confirmation_spec.rb
Labels: approved

#948 CRM457-1579: Alert on deployment failure
  .circleci/config.yml
Labels: approved

#946 CRM457-1662: Add a basic PDF renderer
  .circleci/config.yml
  .gitignore
  Dockerfile
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/custom/print-friendly.scss
  app/controllers/prior_authority/applications_controller.rb
  app/helpers/application_helper.rb
  app/services/pdf_service.rb
  app/views/layouts/nsm.html.erb
  app/views/layouts/pdf.html.erb
  app/views/prior_authority/applications/_application_details.html.erb
  app/views/prior_authority/applications/pdf.html.erb
  app/views/prior_authority/applications/response_summaries/_assessed.html.erb
  app/views/prior_authority/applications/response_summaries/_expired.html.erb
  app/views/prior_authority/applications/response_summaries/_sent_back.html.erb
  app/views/prior_authority/applications/show.html.erb
  app/views/prior_authority/applications/state_summaries/_auto_grant.html.erb
  app/views/prior_authority/applications/state_summaries/_expired.html.erb
  app/views/prior_authority/applications/state_summaries/_granted.html.erb
  app/views/prior_authority/applications/state_summaries/_part_grant.html.erb
  app/views/prior_authority/applications/state_summaries/_provider_updated.html.erb
  app/views/prior_authority/applications/state_summaries/_rejected.html.erb
  app/views/prior_authority/applications/state_summaries/_sent_back.html.erb
  app/views/prior_authority/applications/state_summaries/_submitted.html.erb
  config/locales/en.yml
  config/locales/en/nsm.yml
  config/locales/en/prior_authority.yml
  config/routes.rb
  package.json
  spec/lib/tasks/submit_dummy_data_spec.rb
  spec/system/prior_authority/view_applications_spec.rb
  yarn.lock
Labels: approved, In QA

#949 CRM457-1655: Populate accessibility statement
  app/views/about/accessibility.en.html.erb
Labels: approved, In QA

#951 CRM457-1667: Link to documents on all summary cards
  app/presenters/prior_authority/check_answers/alternative_quotes_card.rb
  app/presenters/prior_authority/check_answers/base.rb
  app/presenters/prior_authority/check_answers/compact_further_information_card.rb
  app/presenters/prior_authority/check_answers/further_information_card.rb
  app/presenters/prior_authority/check_answers/primary_quote_card.rb
  app/presenters/prior_authority/check_answers/reason_why_card.rb
  app/views/prior_authority/steps/alternative_quotes/_quote_summary.html.erb
  app/views/prior_authority/steps/primary_quote_summary/_service_cost_card.html.erb
  spec/presenters/prior_authority/check_answers/alternative_quotes_card_spec.rb
  spec/presenters/prior_authority/check_answers/further_information_card_spec.rb
  spec/presenters/prior_authority/check_answers/primary_quote_card_spec.rb
  spec/presenters/prior_authority/check_answers/reason_why_card_spec.rb
  spec/system/prior_authority/view_applications_spec.rb
Labels: approved, In QA

#954 CRM457-1691: Handle filenames with commas
  app/controllers/prior_authority/downloads_controller.rb
Labels: ready for review

#953 CRM457-1677: Granted claim comments
  app/presenters/nsm/check_answers/application_status_card.rb
  app/services/nsm/assessment_syncer.rb
  spec/jobs/pull_updates_spec.rb
  spec/presenters/nsm/check_answers/application_status_card_spec.rb
  spec/services/nsm/assessment_syncer_spec.rb
Labels: approved, In QA
