Repository ministryofjustice/laa-submit-crime-forms, pull requests merged in 2024-02, with the labels that each got.

#475 CRM457-1017: Additional cost screens
  app/controllers/prior_authority/applications_controller.rb
  app/controllers/prior_authority/steps/additional_cost_details_controller.rb
  app/controllers/prior_authority/steps/additional_costs_controller.rb
  app/forms/prior_authority/steps/additional_costs/detail_form.rb
  app/forms/prior_authority/steps/additional_costs/overview_form.rb
  app/helpers/application_helper.rb
  app/models/additional_cost.rb
  app/models/prior_authority_application.rb
  app/presenters/prior_authority/primary_quote_summary.rb
  app/presenters/prior_authority/tasks/base.rb
  app/presenters/prior_authority/tasks/case_and_hearing_detail.rb
  app/presenters/prior_authority/tasks/case_contact.rb
  app/presenters/prior_authority/tasks/client_detail.rb
  app/presenters/prior_authority/tasks/primary_quote.rb
  app/presenters/prior_authority/tasks/reason_why.rb
  app/presenters/prior_authority/tasks/ufn.rb
  app/services/decisions/back_decision_tree.rb
  app/services/decisions/decision_tree.rb
  app/services/decisions/dsl_decision_tree.rb
  app/views/prior_authority/applications/offboard.html.erb
  app/views/prior_authority/steps/additional_cost_details/confirm_delete.html.erb
  app/views/prior_authority/steps/additional_cost_details/edit.html.erb
  app/views/prior_authority/steps/additional_costs/_cost_summary.html.erb
  app/views/prior_authority/steps/additional_costs/edit.html.erb
  app/views/prior_authority/steps/primary_quote_summary/_additional_cost_card.html.erb
  app/views/prior_authority/steps/primary_quote_summary/show.html.erb
  config/locales/en/errors.yml
  config/locales/en/prior_authority/steps.yml
  config/routes.rb
  db/migrate/20240129090748_create_additional_costs.rb
  db/schema.rb
  gems/laa_multi_step_forms/Gemfile.lock
  spec/controllers/prior_authority/reason_why_controller_spec.rb
  spec/decisions/dsl_decision_tree_spec.rb
  spec/support/steps/a_generic_decision.rb
  spec/system/prior_authority/additional_costs_spec.rb
  spec/system/prior_authority/primary_quote_summary_spec.rb
  spec/system/prior_authority/service_cost_spec.rb
  spec/system/prior_authority/travel_detail_spec.rb
  spec/system/support/prior_authority/step_helpers.rb
Labels: approved

#470 CRM457-1016: Travel cost screens
  app/controllers/prior_authority/applications_controller.rb
  app/controllers/prior_authority/steps/additional_cost_details_controller.rb
  app/controllers/prior_authority/steps/additional_costs_controller.rb
  app/controllers/prior_authority/steps/delete_travel_controller.rb
  app/controllers/prior_authority/steps/travel_detail_controller.rb
  app/forms/prior_authority/steps/additional_costs/detail_form.rb
  app/forms/prior_authority/steps/additional_costs/overview_form.rb
  app/forms/prior_authority/steps/delete_travel_form.rb
  app/forms/prior_authority/steps/travel_detail_form.rb
  app/helpers/application_helper.rb
  app/models/additional_cost.rb
  app/models/prior_authority_application.rb
  app/presenters/prior_authority/primary_quote_summary.rb
  app/presenters/prior_authority/tasks/base.rb
  app/presenters/prior_authority/tasks/case_and_hearing_detail.rb
  app/presenters/prior_authority/tasks/case_contact.rb
  app/presenters/prior_authority/tasks/client_detail.rb
  app/presenters/prior_authority/tasks/primary_quote.rb
  app/presenters/prior_authority/tasks/reason_why.rb
  app/presenters/prior_authority/tasks/ufn.rb
  app/services/decisions/back_decision_tree.rb
  app/services/decisions/decision_tree.rb
  app/services/decisions/dsl_decision_tree.rb
  app/views/prior_authority/applications/offboard.html.erb
  app/views/prior_authority/steps/additional_cost_details/confirm_delete.html.erb
  app/views/prior_authority/steps/additional_cost_details/edit.html.erb
  app/views/prior_authority/steps/additional_costs/_cost_summary.html.erb
  app/views/prior_authority/steps/additional_costs/edit.html.erb
  app/views/prior_authority/steps/delete_travel/edit.html.erb
  app/views/prior_authority/steps/primary_quote_summary/_additional_cost_card.html.erb
  app/views/prior_authority/steps/primary_quote_summary/_travel_cost_card.html.erb
  app/views/prior_authority/steps/primary_quote_summary/show.html.erb
  app/views/prior_authority/steps/travel_detail/edit.html.erb
  config/locales/en/errors.yml
  config/locales/en/prior_authority/steps.yml
  config/routes.rb
  db/migrate/20240126150501_add_hourly_travel_costs_to_prior_authority_application.rb
  db/migrate/20240129090748_create_additional_costs.rb
  db/schema.rb
  gems/laa_multi_step_forms/Gemfile.lock
  spec/controllers/prior_authority/reason_why_controller_spec.rb
  spec/decisions/dsl_decision_tree_spec.rb
  spec/forms/prior_authority/steps/travel_detail_form_spec.rb
  spec/support/steps/a_generic_decision.rb
  spec/system/prior_authority/additional_costs_spec.rb
  spec/system/prior_authority/primary_quote_summary_spec.rb
  spec/system/prior_authority/service_cost_spec.rb
  spec/system/prior_authority/travel_detail_spec.rb
  spec/system/support/prior_authority/step_helpers.rb
Labels: approved

#501 CRM457-988 addendum: Test file upload
  spec/system/prior_authority/reason_why_spec.rb
Labels: approved

#502 CRM457-1015: Give priority to text field rather than hidden select
  app/forms/prior_authority/steps/primary_quote_form.rb
  spec/forms/prior_authority/steps/primary_quote_form_spec.rb
Labels: approved

#477 CRM457-982, 1014: Find and delete an application
  app/controllers/prior_authority/applications_controller.rb
  app/helpers/sortable_table_helper.rb
  app/models/prior_authority_application.rb
  app/views/prior_authority/applications/assessed.html.erb
  app/views/prior_authority/applications/confirm_delete.html.erb
  app/views/prior_authority/applications/draft.html.erb
  app/views/prior_authority/applications/frame_contents/_assessed.html.erb
  app/views/prior_authority/applications/frame_contents/_draft.html.erb
  app/views/prior_authority/applications/frame_contents/_submitted.html.erb
  app/views/prior_authority/applications/index.html.erb
  app/views/prior_authority/applications/submitted.html.erb
  config/locales/en/prior_authority.yml
  config/routes.rb
  spec/system/prior_authority/application_lists_spec.rb
  spec/system/prior_authority/create_application_spec.rb
  spec/system/prior_authority/delete_application_spec.rb
  spec/system/support/capybara_setup.rb
Labels: approved

#513 Add shared date and time formats and use
  app/mailers/claim_submission_mailer.rb
  app/presenters/nsm/check_answers/application_status_card.rb
  app/presenters/nsm/check_answers/case_details_card.rb
  app/presenters/nsm/check_answers/case_disposal_card.rb
  app/presenters/nsm/check_answers/claim_details_card.rb
  app/presenters/nsm/check_answers/claim_justification_card.rb
  app/presenters/nsm/check_answers/claim_type_card.rb
  app/presenters/nsm/check_answers/hearing_details_card.rb
  app/views/nsm/claims/index.html.erb
  app/views/prior_authority/applications/frame_contents/_assessed.html.erb
  app/views/prior_authority/applications/frame_contents/_draft.html.erb
  app/views/prior_authority/applications/frame_contents/_submitted.html.erb
  config/initializers/time_formats.rb
  spec/mailers/claim_submission_mailer_spec.rb
  spec/presenters/nsm/check_answers/claim_type_card_spec.rb
Labels: approved

#516 crm457-979: namespace tasklist section headers
  app/presenters/nsm/start_page.rb
  app/presenters/prior_authority/start_page.rb
  config/locales/en/tasklist.yml
Labels: approved

#512 CRM457-1040: Fix bug in navigation stack logic
  app/controllers/prior_authority/steps/base_controller.rb
  spec/system/prior_authority/task_list_spec.rb
  spec/system/support/prior_authority/step_helpers.rb
Labels: approved

#490 WIP - [CRM457-1048] better-task-list
  app/controllers/prior_authority/steps/check_answers_controller.rb
  app/presenters/nsm/tasks/case_details.rb
  app/presenters/nsm/tasks/case_disposal.rb
  app/presenters/nsm/tasks/check_answers.rb
  app/presenters/nsm/tasks/claim_confirmation.rb
  app/presenters/nsm/tasks/cost_summary.rb
  app/presenters/nsm/tasks/defendants.rb
  app/presenters/nsm/tasks/disbursements.rb
  app/presenters/nsm/tasks/firm_details.rb
  app/presenters/nsm/tasks/hearing_details.rb
  app/presenters/nsm/tasks/letters_calls.rb
  app/presenters/nsm/tasks/reason_for_claim.rb
  app/presenters/nsm/tasks/solicitor_declaration.rb
  app/presenters/nsm/tasks/supporting_evidence.rb
  app/presenters/nsm/tasks/work_items.rb
  app/presenters/prior_authority/tasks/alternative_quotes.rb
  app/presenters/prior_authority/tasks/case_and_hearing_detail.rb
  app/presenters/prior_authority/tasks/case_contact.rb
  app/presenters/prior_authority/tasks/client_detail.rb
  app/presenters/prior_authority/tasks/primary_quote.rb
  app/presenters/prior_authority/tasks/reason_why.rb
  app/presenters/tasks/generic.rb
  db/schema.rb
  gems/laa_multi_step_forms/Gemfile.lock
  gems/laa_multi_step_forms/app/presenters/task_list/collection.rb
  gems/laa_multi_step_forms/app/presenters/task_list/section.rb
  gems/laa_multi_step_forms/app/presenters/task_list/status_tag.rb
  gems/laa_multi_step_forms/app/presenters/task_list/task.rb
  gems/laa_multi_step_forms/app/presenters/task_list/task_status.rb
  gems/laa_multi_step_forms/app/presenters/tasks/base_task.rb
  gems/laa_multi_step_forms/spec/presenters/task_list/collection_spec.rb
  gems/laa_multi_step_forms/spec/presenters/task_list/section_spec.rb
  gems/laa_multi_step_forms/spec/presenters/task_list/task_spec.rb
  gems/laa_multi_step_forms/spec/presenters/tasks/base_task_spec.rb
  spec/factories/prior_authority_application.rb
  spec/presenters/prior_authority/tasks/reason_why_spec.rb
  spec/steps/nsm/claim_details/presenter_spec.rb
  spec/support/steps/a_task_with_generic_can_start.rb
Labels: approved

#518 CRM457-1110: Default to sorting by most recent
  app/controllers/prior_authority/applications_controller.rb
  app/helpers/sortable_table_helper.rb
  app/views/prior_authority/applications/assessed.html.erb
  app/views/prior_authority/applications/draft.html.erb
  app/views/prior_authority/applications/frame_contents/_assessed.html.erb
  app/views/prior_authority/applications/frame_contents/_draft.html.erb
  app/views/prior_authority/applications/frame_contents/_submitted.html.erb
  app/views/prior_authority/applications/submitted.html.erb
  spec/system/prior_authority/application_lists_spec.rb
Labels: approved

#528 CRM457-1017: Address QA comments
  app/forms/prior_authority/quote_cost_validations.rb
  app/forms/prior_authority/steps/additional_costs/detail_form.rb
  app/forms/prior_authority/steps/quote_cost_form.rb
  app/presenters/prior_authority/tasks/primary_quote.rb
  app/views/prior_authority/steps/additional_cost_details/edit.html.erb
  app/views/prior_authority/steps/service_cost/_items.html.erb
  app/views/prior_authority/steps/service_cost/_time.html.erb
  config/locales/en/errors.yml
  gems/laa_multi_step_forms/app/attributes/type/fully_validatable_integer.rb
  gems/laa_multi_step_forms/app/attributes/type/gbp.rb
  gems/laa_multi_step_forms/app/helpers/laa_multi_step_forms/application_helper.rb
  gems/laa_multi_step_forms/app/validators/is_a_number_validator.rb
  gems/laa_multi_step_forms/config/initializers/attribute_types.rb
  gems/laa_multi_step_forms/spec/attributes/type/fully_validatable_integer_spec.rb
  gems/laa_multi_step_forms/spec/attributes/type/gbp_spec.rb
  gems/laa_multi_step_forms/spec/helpers/application_helper_spec.rb
  gems/laa_multi_step_forms/spec/validators/is_a_number_validator_spec.rb
  spec/system/prior_authority/additional_costs_spec.rb
Labels: approved

#522 [CRM457-988] QA-feedback: Add missing error condition
  app/forms/prior_authority/steps/reason_why_form.rb
  config/locales/en/errors.yml
  spec/forms/prior_authority/steps/reason_why_form_spec.rb
Labels: approved

#534 CRM457-977: Stop auto-casting params to integers
  app/forms/prior_authority/steps/travel_detail_form.rb
  config/locales/en/errors.yml
  config/locales/en/prior_authority/alternative_quotes.yml
  gems/laa_multi_step_forms/app/lib/govuk_design_system_formbuilder/elements/period.rb
  gems/laa_multi_step_forms/app/validators/time_period_validator.rb
  gems/laa_multi_step_forms/spec/lib/govuk_design_system_formbuilder/builder/period_spec.rb
  gems/laa_multi_step_forms/spec/validators/time_period_validator_spec.rb
  spec/forms/prior_authority/steps/travel_detail_form_spec.rb
  spec/system/prior_authority/alternative_quotes_spec.rb
Labels: approved

#535 CRM457-1015: Edge case when delete service name
  app/forms/prior_authority/steps/primary_quote_form.rb
  spec/forms/prior_authority/steps/primary_quote_form_spec.rb
Labels: approved

#514 CRM457-979: Add prior authority check your answers page
  Gemfile
  Gemfile.lock
  app/controllers/prior_authority/steps/check_answers_controller.rb
  app/forms/prior_authority/steps/psychiatric_liaison_form.rb
  app/models/prior_authority_application.rb
  app/presenters/prior_authority/check_answers/alternative_quotes_card.rb
  app/presenters/prior_authority/check_answers/base.rb
  app/presenters/prior_authority/check_answers/case_contact_card.rb
  app/presenters/prior_authority/check_answers/case_detail_card.rb
  app/presenters/prior_authority/check_answers/client_detail_card.rb
  app/presenters/prior_authority/check_answers/hearing_detail_card.rb
  app/presenters/prior_authority/check_answers/next_hearing_card.rb
  app/presenters/prior_authority/check_answers/primary_quote_card.rb
  app/presenters/prior_authority/check_answers/primary_quote_card_summary.rb
  app/presenters/prior_authority/check_answers/reason_why_card.rb
  app/presenters/prior_authority/check_answers/report.rb
  app/presenters/prior_authority/check_answers/ufn_card.rb
  app/presenters/prior_authority/start_page.rb
  app/presenters/prior_authority/tasks/case_and_hearing_detail.rb
  app/presenters/prior_authority/tasks/check_answers.rb
  app/services/decisions/decision_tree.rb
  app/views/prior_authority/steps/check_answers/edit.html.erb
  config/locales/en/generic.yml
  config/locales/en/nsm/check_answers.yml
  config/locales/en/prior_authority/check_answers.yml
  config/locales/en/prior_authority/steps.yml
  config/routes.rb
  spec/factories/prior_authority_application.rb
  spec/forms/prior_authority/steps/psychiatric_liaison_form_spec.rb
  spec/presenters/prior_authority/check_answers/alternative_quotes_card_spec.rb
  spec/presenters/prior_authority/check_answers/case_contact_card_spec.rb
  spec/presenters/prior_authority/check_answers/case_detail_card_spec.rb
  spec/presenters/prior_authority/check_answers/client_detail_card_spec.rb
  spec/presenters/prior_authority/check_answers/hearing_detail_card_spec.rb
  spec/presenters/prior_authority/check_answers/next_hearing_card_spec.rb
  spec/presenters/prior_authority/check_answers/primary_quote_card_spec.rb
  spec/presenters/prior_authority/check_answers/reason_why_card_spec.rb
  spec/presenters/prior_authority/check_answers/report_spec.rb
  spec/presenters/prior_authority/check_answers/ufn_card_spec.rb
  spec/presenters/prior_authority/tasks/check_answers_spec.rb
  spec/system/prior_authority/check_your_answers/no_prison_law_spec.rb
  spec/system/prior_authority/hearing_details_spec.rb
  spec/system/prior_authority/youth_court_spec.rb
  spec/system/support/prior_authority/step_helpers.rb
Labels: approved

#529 [Crm457-1016] bugs
  app/controllers/prior_authority/steps/travel_detail_controller.rb
  app/forms/prior_authority/quote_cost_validations.rb
  app/forms/prior_authority/steps/additional_costs/detail_form.rb
  app/views/prior_authority/steps/travel_detail/edit.html.erb
  config/locales/en/errors.yml
  config/locales/en/prior_authority/alternative_quotes.yml
  gems/laa_multi_step_forms/app/validators/time_period_validator.rb
  gems/laa_multi_step_forms/spec/validators/time_period_validator_spec.rb
  spec/system/prior_authority/travel_detail_spec.rb
Labels: WIP

#543 CRM457-979: Add index to alt quote card
  app/presenters/prior_authority/check_answers/alternative_quotes_card.rb
  config/locales/en/prior_authority/check_answers.yml
  spec/presenters/prior_authority/check_answers/alternative_quotes_card_spec.rb
  spec/system/prior_authority/check_your_answers/no_prison_law_spec.rb
Labels: approved

#544 CRM457-979: Move `actions` header resposibility to cards and add row actions capability
  app/presenters/nsm/check_answers/report.rb
  app/presenters/prior_authority/check_answers/base.rb
  app/presenters/prior_authority/check_answers/primary_quote_card.rb
  app/presenters/prior_authority/check_answers/report.rb
  app/presenters/prior_authority/check_answers/ufn_card.rb
  config/locales/en/generic.yml
  spec/presenters/prior_authority/check_answers/ufn_card_spec.rb
Labels: approved

#540 CRM457-1132: Add confirmations to check your answers
  app/controllers/prior_authority/steps/base_controller.rb
  app/controllers/prior_authority/steps/check_answers_controller.rb
  app/controllers/prior_authority/steps/submission_confirmation_controller.rb
  app/forms/prior_authority/steps/check_answers_form.rb
  app/presenters/prior_authority/check_answers/primary_quote_card.rb
  app/services/decisions/decision_tree.rb
  app/services/submit_to_app_store/prior_authority_payload_builder.rb
  app/views/prior_authority/steps/check_answers/edit.html.erb
  app/views/prior_authority/steps/primary_quote_summary/_service_cost_card.html.erb
  app/views/prior_authority/steps/submission_confirmation/show.html.erb
  config/locales/en/errors.yml
  config/locales/en/prior_authority/check_answers.yml
  config/locales/en/prior_authority/steps.yml
  config/routes.rb
  db/migrate/20240216084333_add_confirmations_to_prior_authority_applications.rb
  db/schema.rb
  gems/laa_multi_step_forms/config/locales/en/helpers.yml
  spec/factories/prior_authority_application.rb
  spec/forms/prior_authority/steps/check_answers_form_spec.rb
  spec/presenters/prior_authority/check_answers/primary_quote_card_spec.rb
  spec/services/submit_to_app_store/prior_authority_payload_builder_spec.rb
  spec/system/prior_authority/check_your_answers/no_prison_law_spec.rb
  spec/system/prior_authority/check_your_answers/prison_law_spec.rb
  spec/system/prior_authority/check_your_answers/submission_spec.rb
  spec/system/prior_authority/primary_quote_spec.rb
  spec/system/support/prior_authority/step_helpers.rb
Labels: approved

#549 CRM457-983 bug: Fix bug in travel costs
  app/forms/prior_authority/steps/alternative_quotes/detail_form.rb
  spec/forms/prior_authority/steps/alternative_quotes/detail_form_spec.rb
Labels: approved

#563 CRM457-978: Make date of next hearing optional
  app/forms/prior_authority/steps/hearing_detail_form.rb
  spec/forms/prior_authority/steps/hearing_detail_form_spec.rb
  spec/system/prior_authority/hearing_details_spec.rb
Labels: approved

#568 CRM457-1061: Temporary dev releases
  .circleci/config.yml
  .github/actions/delete-dev-release/action.yml
  .github/workflows/delete-dev-release.yml
  bin/deploy
  config/database.yml
  config/initializers/sidekiq.rb
  helm_deploy/Chart.lock
  helm_deploy/Chart.yaml
  helm_deploy/charts/postgresql-11.9.13.tgz
  helm_deploy/charts/redis-17.15.2.tgz
  helm_deploy/templates/_helpers.tpl
  helm_deploy/templates/deployment-worker.yaml
  helm_deploy/templates/deployment.yaml
  helm_deploy/values-dev-crm4.yaml
  helm_deploy/values-dev.yaml
  helm_deploy/values-prod.yaml
  helm_deploy/values-uat.yaml
  helm_deploy/values.yaml
Labels: approved

#570 CRM457-1061: Pt 2
  .github/workflows/delete-dev-release.yml
Labels: ready for review

#560 Update GitHub repo name pt2
  .circleci/config.yml
  package.json
Labels: approved

#577 CRM457-1156: optional next hearing date - non-prison law
  app/forms/prior_authority/steps/hearing_detail_form.rb
  app/views/prior_authority/steps/hearing_detail/edit.html.erb
  config/locales/en/errors.yml
  config/locales/en/prior_authority/steps.yml
  spec/forms/prior_authority/steps/hearing_detail_form_spec.rb
  spec/forms/prior_authority/steps/next_hearing_form_spec.rb
  spec/system/prior_authority/hearing_details_spec.rb
  spec/system/support/prior_authority/step_helpers.rb
Labels: approved

#579 CRM457-1139 CRM4 Provider - Copy change to 'New application' button
  config/locales/en/prior_authority.yml
  spec/system/prior_authority/authority_value_spec.rb
  spec/system/prior_authority/create_application_spec.rb
  spec/system/support/prior_authority/step_helpers.rb
Labels: approved

#578 Replace linebreaks in, and sanitize, text fields
  app/presenters/prior_authority/check_answers/base.rb
  app/presenters/prior_authority/check_answers/primary_quote_card.rb
  app/presenters/prior_authority/check_answers/reason_why_card.rb
  spec/presenters/prior_authority/check_answers/primary_quote_card_spec.rb
  spec/presenters/prior_authority/check_answers/reason_why_card_spec.rb
  spec/system/prior_authority/check_your_answers/no_prison_law_spec.rb
Labels: approved

#589 BUG: Fix field missing from payload
  app/services/submit_to_app_store/prior_authority_payload_builder.rb
  spec/services/submit_to_app_store/prior_authority_payload_builder_spec.rb
Labels: approved

#590 CRM457-1156: Add display logic for next hearing date
  app/presenters/prior_authority/check_answers/hearing_detail_card.rb
  spec/presenters/prior_authority/check_answers/hearing_detail_card_spec.rb
Labels: ready for review

#592 CRM457-1169 Send item type in payload
  app/services/submit_to_app_store/prior_authority/quote_payload_builder.rb
  spec/services/submit_to_app_store/prior_authority_payload_builder_spec.rb
Labels: approved

#597 Add container `securityContext` to all containers
  helm_deploy/templates/deployment-worker.yaml
  helm_deploy/templates/deployment.yaml
Labels: ready for review

#596 Setup and clamav test amendments
  .env.development
  .env.test
  Brewfile
  README.md
  bin/install_clamav_on_mac
  spec/fixtures/files/malware.doc
  spec/services/file_upload/file_uploader_spec.rb
Labels: ready for review

#599 Bump ruby 3.2.2 to 3.3.0
  .circleci/config.yml
  .rubocop.yml
  .ruby-version
  Dockerfile
  Gemfile.lock
  README.md
  gems/laa_multi_step_forms/.rubocop.yml
  gems/laa_multi_step_forms/laa_multi_step_forms.gemspec
Labels: approved

#561 CRM457-983: Add more validations and formatting
  app/forms/prior_authority/steps/additional_costs/detail_form.rb
  app/forms/prior_authority/steps/alternative_quotes/detail_form.rb
  app/forms/prior_authority/steps/primary_quote_form.rb
  app/forms/prior_authority/steps/quote_cost_form.rb
  app/forms/prior_authority/steps/service_cost_form.rb
  app/forms/prior_authority/steps/travel_detail_form.rb
  app/lib/prior_authority/service_type_rule.rb
  app/value_objects/prior_authority/quote_services.rb
  app/views/prior_authority/steps/alternative_quote_details/edit.html.erb
  app/views/prior_authority/steps/primary_quote_summary/_travel_cost_card.html.erb
  app/views/prior_authority/steps/travel_detail/edit.html.erb
  config/locales/en/errors.yml
  config/locales/en/helpers.yml
  config/locales/en/prior_authority/alternative_quotes.yml
  config/locales/en/prior_authority/steps.yml
  spec/forms/prior_authority/steps/alternative_quotes/detail_form_spec.rb
  spec/forms/prior_authority/steps/primary_quote_form_spec.rb
  spec/system/prior_authority/service_cost_spec.rb
  spec/system/support/prior_authority/step_helpers.rb
Labels: approved, In QA

#603 CRM457-1147: Change dependabot cadence
  .github/dependabot.yml
Labels: ready for review

#605 CRM457-1103: Switch from importmap to propshaft
  .circleci/config.yml
  .gitignore
  Gemfile
  Gemfile.lock
  Procfile.dev
  README.md
  app/assets/config/manifest.js
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/print.scss
  app/javascript/application.js
  app/views/nsm/steps/case_details/edit.html.erb
  app/views/nsm/steps/supporting_evidence/edit.html.erb
  app/views/prior_authority/steps/reason_why/edit.html.erb
  bin/dev
  bin/importmap
  config/application.rb
  config/importmap.rb
  config/initializers/assets.rb
  config/initializers/dartsass.rb
  gems/laa_multi_step_forms/.ruby-version
  gems/laa_multi_step_forms/Gemfile
  gems/laa_multi_step_forms/Gemfile.lock
  gems/laa_multi_step_forms/app/assets/stylesheets/laa_multi_step_forms/local/govuk.scss
  gems/laa_multi_step_forms/app/views/layouts/govuk_template.html.erb
  gems/laa_multi_step_forms/laa_multi_step_forms.gemspec
  gems/laa_multi_step_forms/spec/dummy/app/channels/application_cable/channel.rb
  gems/laa_multi_step_forms/spec/dummy/app/channels/application_cable/connection.rb
  gems/laa_multi_step_forms/spec/dummy/config/initializers/assets.rb
  helm_deploy/templates/deployment.yaml
  package.json
  yarn.lock
Labels: ready for review

#609 Fix erroneous append of js command in `Procfile.dev`
  Procfile.dev
Labels: approved

#610 CRM457-1092: Add nonces and CSP
  app/views/nsm/claims/index.html.erb
  app/views/nsm/steps/case_details/edit.html.erb
  app/views/nsm/steps/supporting_evidence/edit.html.erb
  app/views/prior_authority/steps/reason_why/edit.html.erb
  config/initializers/content_security_policy.rb
  gems/laa_multi_step_forms/app/views/layouts/_header_navigation.html.erb
  gems/laa_multi_step_forms/app/views/layouts/govuk_template.html.erb
Labels: approved

#598 [CRM457-1143] Fix back button functionality from index
  app/javascript/application.js
  app/views/prior_authority/applications/frame_contents/_draft.html.erb
  app/views/prior_authority/applications/index.html.erb
Labels: approved

#611 CRM457-1082: Add new crown logo
  gems/laa_multi_step_forms/app/views/layouts/govuk_template.html.erb
Labels: ready for review
