Repository ministryofjustice/laa-submit-crime-forms, pull requests merged in 2024-08, with the labels that each got.

#1022 [CRM457-1778] Onboard additional providers (TRANCHE 10)
  config/gatekeeper_crm4.yml
Labels: DO NOT MERGE

#1045 CRM457-1758: Fix table links aria label Ids
  app/helpers/sortable_table_helper.rb
  app/views/nsm/steps/disbursements/edit.html.erb
Labels: ready for review

#1039 CRM457-1812: Store nsm disbursement position on submission
  app/forms/nsm/steps/solicitor_declaration_form.rb
  app/models/claim.rb
  db/migrate/20240806082652_backfill_disbursement_position.rb
  db/schema.rb
  spec/models/claim_spec.rb
Labels: approved

#1049 CRM457-1831: Prog and prom questions
  app/controllers/nsm/steps/case_transfer_controller.rb
  app/controllers/nsm/steps/court_area_controller.rb
  app/controllers/nsm/steps/office_area_controller.rb
  app/forms/nsm/steps/case_transfer_form.rb
  app/forms/nsm/steps/claim_type_form.rb
  app/forms/nsm/steps/court_area_form.rb
  app/forms/nsm/steps/office_area_form.rb
  app/models/claim.rb
  app/models/concerns/stage_reached_calculatable.rb
  app/presenters/nsm/check_answers/claim_type_card.rb
  app/presenters/nsm/check_answers/read_only_report.rb
  app/presenters/nsm/check_answers/report.rb
  app/presenters/nsm/start_page.rb
  app/presenters/nsm/tasks/claim_type.rb
  app/services/decisions/back_decision_tree.rb
  app/services/decisions/decision_tree.rb
  app/services/submit_to_app_store/nsm_payload_builder.rb
  app/views/nsm/steps/case_transfer/edit.html.erb
  app/views/nsm/steps/check_answers/show.html.erb
  app/views/nsm/steps/court_area/edit.html.erb
  app/views/nsm/steps/office_area/edit.html.erb
  config/locales/en/errors.yml
  config/locales/en/nsm/check_answers.yml
  config/locales/en/nsm/steps.yml
  config/locales/en/tasklist.yml
  config/routes.rb
  db/migrate/20240807155517_add_prog_fields_to_claim.rb
  db/schema.rb
  gems/laa_multi_step_forms/app/views/laa_multi_step_forms/task_list/show.html.erb
  spec/decisions/back_decision_tree_spec.rb
  spec/factories/claims.rb
  spec/forms/nsm/steps/claim_type_form_spec.rb
  spec/forms/nsm/steps/court_area_form_spec.rb
  spec/forms/nsm/steps/office_area_form_spec.rb
  spec/presenter/nsm/steps/claim_type_presenter_spec.rb
  spec/presenters/nsm/check_answers/claim_type_card_spec.rb
  spec/presenters/nsm/check_answers/read_only_report_spec.rb
  spec/presenters/nsm/check_answers/report_spec.rb
  spec/services/submit_to_app_store/nsm_payload_builder_spec.rb
  spec/system/nsm/prog_and_prom_spec.rb
Labels: ready for review

#1053 CRM457-1816: Use "magic bytes" to check file type if possible
  Gemfile
  Gemfile.lock
  app/controllers/concerns/multi_file_uploadable.rb
  app/forms/concerns/document_uploadable.rb
  spec/fixtures/files/actually_a_zip.pdf
  spec/forms/prior_authority/steps/alternative_quotes/detail_form_spec.rb
  spec/forms/prior_authority/steps/primary_quote_form_spec.rb
  spec/support/steps/a_multi_file_upload_controller.rb
  spec/system/nsm/supporting_evidence_spec.rb
Labels: ready for review

#1054 CRM457-1841: Use calculated stage instead of explicit 'in area' question
  app/forms/nsm/steps/hearing_details_form.rb
  app/forms/nsm/steps/work_item_form.rb
  app/models/concerns/stage_reached_calculatable.rb
  app/models/work_item.rb
  app/presenters/nsm/check_answers/hearing_details_card.rb
  app/value_objects/work_types.rb
  app/views/nsm/steps/hearing_details/edit.html.erb
  app/views/nsm/steps/work_items/edit.html.erb
  config/locales/en/errors.yml
  config/locales/en/helpers.yml
  config/locales/en/nsm/check_answers.yml
  db/migrate/20240808140456_remove_in_area_from_claims.rb
  db/schema.rb
  gems/laa_multi_step_forms/app/views/laa_multi_step_forms/task_list/show.html.erb
  spec/factories/claims.rb
  spec/factories/work_items.rb
  spec/forms/nsm/steps/hearing_details_form_spec.rb
  spec/forms/nsm/steps/work_items_add_form_spec.rb
  spec/presenters/nsm/check_answers/hearing_details_card_spec.rb
  spec/presenters/nsm/check_answers/work_items_card_spec.rb
  spec/presenters/nsm/cost_summary/disbursements_spec.rb
  spec/presenters/nsm/cost_summary/work_items_spec.rb
  spec/services/submit_to_app_store/nsm_payload_builder_spec.rb
  spec/system/nsm/hearing_details_spec.rb
  spec/system/nsm/work_items_spec.rb
Labels: approved, In QA

#1055 CRM457-1785: Stop looking at events in payload
  app/services/nsm/assessment_syncer.rb
  app/services/prior_authority/assessment_syncer.rb
  spec/jobs/pull_updates_spec.rb
  spec/services/nsm/assessment_syncer_spec.rb
  spec/services/prior_authority/assessment_syncer_spec.rb
Labels: ready for review

#1059 CRM457-1847: Remove 'retry_on'
  app/jobs/submit_to_app_store.rb
Labels: ready for review

#1056 CRM457-1838: Add client side validation of single file uploads
  app/javascript/single-file-upload-validator.js
  app/views/prior_authority/steps/alternative_quote_details/edit.html.erb
  app/views/prior_authority/steps/primary_quote/edit.html.erb
  spec/system/prior_authority/primary_quote_spec.rb
Labels: approved, In QA

#1060 CRM457-1788: Change maat naming
  config/locales/en/errors.yml
  config/locales/en/prior_authority/check_answers.yml
  config/locales/en/prior_authority/steps.yml
  spec/forms/nsm/steps/defendant_details_form_spec.rb
  spec/forms/prior_authority/steps/case_detail/defendant_form_spec.rb
  spec/forms/prior_authority/steps/case_detail_form_spec.rb
  spec/system/prior_authority/case_detail_spec.rb
  spec/system/prior_authority/check_your_answers/no_prison_law_spec.rb
  spec/system/support/prior_authority/step_helpers.rb
Labels: approved

#1062 CRM457-1858: Move perform_laters out of transactions
  app/forms/nsm/steps/solicitor_declaration_form.rb
  app/forms/prior_authority/steps/check_answers_form.rb
  app/services/app_store_client.rb
Labels: approved

#1064 [CRM457-1851] Don't show adjusted work items summary if no adjustments
  app/views/nsm/steps/view_claim/_allowed_work_items.html.erb
Labels: approved

#1067 CRM457-1828: Validation message when decimal entered into items field
  app/forms/prior_authority/quote_cost_validations.rb
  app/validators/cost_item_type_dependant_validator.rb
  app/validators/item_type_dependant_validator.rb
  config/locales/en/errors.yml
  spec/validators/cost_item_type_dependant_validator_spec.rb
  spec/validators/item_type_dependant_validator_spec.rb
Labels: approved

#1012 [CRM457-789] letters calls validation if uplift apply true
  app/forms/nsm/steps/letters_calls_form.rb
  config/locales/en/errors.yml
  config/locales/en/helpers.yml
  spec/forms/nsm/steps/letters_calls_form_spec.rb
  spec/system/nsm/letters_calls_spec.rb
Labels: approved

#1071 CRM457-1804: Fix case of status label
  config/locales/en/nsm/claims.yml
  spec/presenters/nsm/check_answers/application_status_card_spec.rb
Labels: approved

#1063 CRM457-1765: Update cost summary formatting
  app/models/claim.rb
  app/presenters/nsm/check_answers/cost_summary_card.rb
  app/presenters/nsm/cost_summary/base.rb
  app/presenters/nsm/cost_summary/disbursements.rb
  app/presenters/nsm/cost_summary/letters_calls.rb
  app/presenters/nsm/cost_summary/report.rb
  app/presenters/nsm/cost_summary/work_items.rb
  app/views/nsm/steps/check_answers/show.html.erb
  app/views/nsm/steps/cost_summary/_summary_table.html.erb
  app/views/nsm/steps/cost_summary/show.html.erb
  config/locales/en/nsm/steps.yml
  config/locales/en/nsm/summary.yml
  spec/presenters/nsm/check_answers/cost_summary_card_spec.rb
  spec/presenters/nsm/cost_summary/letters_and_calls_spec.rb
  spec/presenters/nsm/cost_summary/report_spec.rb
  spec/presenters/nsm/cost_summary/work_items_spec.rb
  spec/system/nsm/check_answers_spec.rb
  spec/system/nsm/cost_summary_spec.rb
  spec/system/nsm/view_claim_spec.rb
Labels: approved, In QA

#1072 CRM457-1850: Reenable disabled forms on browser back
  app/javascript/handle-forms.js
Labels: approved

#1073 CRM457-1233: Properly redirect after deleting a disbursement
  app/services/decisions/decision_tree.rb
  spec/decisions/decision_tree_spec.rb
Labels: approved

#1077 CRM7: Adjust contact email for Further Information
  app/presenters/nsm/check_answers/application_status_card.rb
  spec/presenters/nsm/check_answers/application_status_card_spec.rb
Labels: ready for review

#957 CRM457-1689: Changeable work types
  app/models/concerns/work_item_costs.rb
  app/models/work_item.rb
  app/services/nsm/assessment_syncer.rb
  app/services/submit_to_app_store/nsm_payload_builder.rb
  app/views/nsm/steps/view_claim/_allowed_work_items.html.erb
  app/views/nsm/steps/view_claim/work_item.html.erb
  config/locales/en/nsm/view_claim.yml
  db/migrate/20240628134832_add_allowed_work_type_to_work_items.rb
  db/schema.rb
  spec/services/nsm/assessment_syncer_spec.rb
  spec/services/submit_to_app_store/nsm_payload_builder_spec.rb
  spec/system/nsm/view_claim_spec.rb
Labels: approved, In QA

#1078 CRM457-1506: Show error we control if login fails
  app/controllers/providers/omniauth_callbacks_controller.rb
  config/locales/en/errors.yml
Labels: approved

#1082 CMR457-1812: Update work item positions on submission of NSM claim
  .rubocop_todo.yml
  app/forms/nsm/steps/solicitor_declaration_form.rb
  app/models/claim.rb
  db/migrate/20240819104601_backfill_work_item_position.rb
  db/schema.rb
  spec/models/claim_spec.rb
  spec/system/nsm/solicitor_declaration_spec.rb
Labels: ready for review

#1076 CRM457-1808: Constrain long lines without whitespace in tables
  app/assets/stylesheets/custom/govuk-table.scss
Labels: ready for review

#1092 CRM457-1905: Fix locking issues
  app/forms/prior_authority/steps/check_answers_form.rb
  app/jobs/submit_to_app_store.rb
  spec/jobs/submit_to_app_store_spec.rb
Labels: approved

#1093 CRM457-1905b: Remove redundant code
  app/forms/prior_authority/steps/check_answers_form.rb
  app/models/prior_authority_application.rb
  app/services/submit_to_app_store/prior_authority_payload_builder.rb
  gems/laa_multi_step_forms/Gemfile.lock
  gems/laa_multi_step_forms/app/forms/steps/base_form_object.rb
  gems/laa_multi_step_forms/spec/forms/steps/base_form_object_spec.rb
  gems/laa_multi_step_forms/spec/forms/steps/has_one_association_spec.rb
  spec/factories/prior_authority_application.rb
  spec/services/submit_to_app_store/prior_authority/event_builder_spec.rb
  spec/services/submit_to_app_store/prior_authority_payload_builder_spec.rb
Labels: approved

#1085 CRM457-1879: Adjust UI for work items with changed types
  app/models/concerns/work_item_costs.rb
  app/models/work_item.rb
  app/presenters/nsm/allowed_work_items/summary_table.rb
  app/presenters/nsm/allowed_work_items/table.rb
  app/presenters/nsm/check_answers/cost_summary_card.rb
  app/services/sorters/work_items_sorter.rb
  app/views/nsm/steps/view_claim/_allowed_work_items.html.erb
  app/views/nsm/steps/view_claim/_work_items.html.erb
  app/views/nsm/steps/view_claim/work_item.html.erb
  config/locales/en/nsm/steps/work_items.yml
  config/locales/en/nsm/view_claim.yml
  spec/presenters/nsm/allowed_work_items/summary_table_spec.rb
  spec/presenters/nsm/allowed_work_items/table_spec.rb
  spec/presenters/nsm/check_answers/cost_summary_card_spec.rb
  spec/system/nsm/view_claim_spec.rb
Labels: approved, In QA

#1100 CRM457-1867: Add dedicated contact details screen
  app/controllers/nsm/steps/contact_details_controller.rb
  app/controllers/nsm/steps/firm_details_controller.rb
  app/forms/nsm/steps/contact_details_form.rb
  app/forms/nsm/steps/firm_details/solicitor_form.rb
  app/presenters/nsm/check_answers/your_details_card.rb
  app/presenters/nsm/tasks/firm_details.rb
  app/services/decisions/back_decision_tree.rb
  app/services/decisions/decision_tree.rb
  app/views/nsm/steps/contact_details/edit.html.erb
  app/views/nsm/steps/firm_details/edit.html.erb
  config/locales/en/errors.yml
  config/locales/en/helpers.yml
  config/locales/en/nsm/check_answers.yml
  config/locales/en/nsm/steps.yml
  config/routes.rb
  spec/decisions/back_decision_tree_spec.rb
  spec/decisions/decision_tree_spec.rb
  spec/factories/claims.rb
  spec/forms/nsm/steps/contact_details_form_spec.rb
  spec/forms/nsm/steps/firm_details/solicitor_form_spec.rb
  spec/presenter/nsm/steps/firm_details_presenter_spec.rb
  spec/presenters/nsm/check_answers/your_details_card_spec.rb
  spec/services/submit_to_app_store/nsm_payload_builder_spec.rb
  spec/system/nsm/contact_details_spec.rb
  spec/system/nsm/firm_details_spec.rb
  spec/system/nsm/office_code_spec.rb
Labels: approved, In QA

#1105 CRM457-1906: Better isolate long-line table fix
  app/assets/stylesheets/custom/govuk-table.scss
  app/assets/stylesheets/custom/govuk-width.scss
  app/presenters/nsm/allowed_work_items/table.rb
  spec/presenters/nsm/allowed_work_items/table_spec.rb
Labels: approved

#1108 CRM457-1923: Fix incorrect numeric column
  app/views/nsm/steps/view_claim/_allowed_disbursements.html.erb
  app/views/nsm/steps/view_claim/_disbursements.html.erb
Labels: approved, In QA

#1094 CRM457-1861: Move office code question
  app/presenters/nsm/check_answers/claim_type_card.rb
  app/presenters/nsm/check_answers/your_details_card.rb
  app/presenters/nsm/tasks/claim_type.rb
  app/presenters/nsm/tasks/firm_details.rb
  app/services/decisions/back_decision_tree.rb
  app/services/decisions/decision_tree.rb
  app/views/nsm/steps/office_code/edit.html.erb
  config/locales/en/nsm/check_answers.yml
  spec/presenter/nsm/steps/claim_type_presenter_spec.rb
  spec/presenter/nsm/steps/firm_details_presenter_spec.rb
  spec/presenters/nsm/check_answers/claim_type_card_spec.rb
  spec/presenters/nsm/check_answers/your_details_card_spec.rb
  spec/system/nsm/office_code_spec.rb
Labels: approved, In QA

#1109 CRM457-1554: More FI details
  app/models/prior_authority_application.rb
  app/presenters/prior_authority/check_answers/further_information_card.rb
  app/presenters/prior_authority/check_answers/incorrect_information_card.rb
  app/presenters/prior_authority/check_answers/report.rb
  app/views/prior_authority/applications/response_summaries/_sent_back.html.erb
  config/locales/en/prior_authority.yml
  config/locales/en/prior_authority/check_answers.yml
  spec/factories/incorrect_informations.rb
  spec/presenters/prior_authority/check_answers/report_spec.rb
  spec/services/submit_to_app_store/prior_authority_payload_builder_spec.rb
  spec/system/prior_authority/check_your_answers/sent_back_for_further_info_spec.rb
  spec/system/prior_authority/view_applications_spec.rb
Labels: approved, In QA

#1110 CRM457-1704: Alert us and user if redis broken
  config/environments/production.rb
  public/500.html
Labels: ready for review

#1115 CRM457-1936: Use find or create within the lock
  app/services/prior_authority/assessment_syncer.rb
Labels: approved

#1113 CRM457-1864: Wait for Clamby in check for readiness
  app/controllers/healthcheck_controller.rb
  config/environments/production.rb
  config/initializers/lograge.rb
  config/initializers/sentry.rb
  config/routes.rb
  helm_deploy/templates/deployment.yaml
  spec/controllers/healthcheck_controller_spec.rb
Labels: approved

#1080 Crm457 1403/duplication in dropdown
  app/forms/prior_authority/steps/case_detail_form.rb
  app/forms/prior_authority/steps/primary_quote_form.rb
  app/views/prior_authority/steps/primary_quote/edit.html.erb
  db/schema.rb
  gems/laa_multi_step_forms/app/helpers/laa_multi_step_forms/application_helper.rb
  gems/laa_multi_step_forms/spec/helpers/application_helper_spec.rb
  spec/forms/prior_authority/steps/primary_quote_form_spec.rb
  spec/system/prior_authority/duplicates_in_dropdown_spec.rb
Labels: approved, In QA

#1117 CRM457-1921: Use correct links for adjustment review
  .rubocop.yml
  app/presenters/nsm/check_answers/application_status_card.rb
  spec/presenters/nsm/check_answers/application_status_card_spec.rb
Labels: approved

#1127 CRM457-1910: Add integration test for notification banner
  spec/system/notification_banner_spec.rb
Labels: approved

#1129 CRM457-1864: Wait for Clamby.safe? to actually succeed
  app/controllers/healthcheck_controller.rb
  spec/controllers/healthcheck_controller_spec.rb
Labels: approved

#1114 CMR457-1907: Enable maintenance mode on production
  config/feature_flags.yml
Labels: DO NOT MERGE

#1126 CRM457-1845: Uplift validation
  app/forms/nsm/steps/work_item_form.rb
  app/views/nsm/steps/work_item/edit.html.erb
  config/locales/en/errors.yml
  config/locales/en/helpers.yml
  spec/forms/nsm/steps/work_items_add_form_spec.rb
  spec/system/nsm/work_items_spec.rb
Labels: approved, In QA

#1133 CRM457-1885: Make rake tasks work with current year
  lib/test_data/nsm_builder.rb
  lib/test_data/pa_builder.rb
  spec/lib/test_data/nsm_builder_spec.rb
  spec/lib/test_data/pa_builder_spec.rb
Labels: approved

#1138 Add notification for Production DB Upgrade
  config/notification_banner.yml
Labels: approved
