Repository ministryofjustice/laa-submit-crime-forms, pull requests merged in 2024-03, with the labels that each got.

#576 CRM457-1158: Readonly summary page for submitted applications
  .rubocop.yml
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/custom/asides.scss
  app/assets/stylesheets/custom/print-friendly.scss
  app/controllers/prior_authority/applications_controller.rb
  app/forms/nsm/steps/letters_calls_form.rb
  app/lib/laa_portal/saml_setup.rb
  app/presenters/prior_authority/check_answers/alternative_quotes_card.rb
  app/presenters/prior_authority/check_answers/hearing_detail_card.rb
  app/presenters/prior_authority/check_answers/primary_quote_card.rb
  app/presenters/prior_authority/check_answers/reason_why_card.rb
  app/presenters/prior_authority/check_answers/report.rb
  app/presenters/prior_authority/check_answers/ufn_card.rb
  app/views/prior_authority/applications/frame_contents/_submitted.html.erb
  app/views/prior_authority/applications/show.html.erb
  app/views/prior_authority/steps/additional_costs/_cost_summary.html.erb
  app/views/prior_authority/steps/additional_costs/_subtable.html.erb
  app/views/prior_authority/steps/alternative_quotes/_quote_summary.html.erb
  app/views/prior_authority/steps/check_answers/_alternative_quotes.html.erb
  app/views/prior_authority/steps/check_answers/_primary_quote.html.erb
  app/views/prior_authority/steps/check_answers/_primary_quote_details.html.erb
  app/views/prior_authority/steps/check_answers/edit.html.erb
  app/views/prior_authority/steps/primary_quote_summary/_service_cost_card.html.erb
  app/views/prior_authority/steps/primary_quote_summary/_service_cost_subtable.html.erb
  app/views/prior_authority/steps/primary_quote_summary/_travel_cost_card.html.erb
  app/views/prior_authority/steps/primary_quote_summary/_travel_cost_subtable.html.erb
  config/locales/en/prior_authority.yml
  config/locales/en/prior_authority/check_answers.yml
  config/locales/en/prior_authority/steps.yml
  spec/presenters/prior_authority/check_answers/reason_why_card_spec.rb
  spec/system/prior_authority/application_lists_spec.rb
Labels: approved, In QA

#615 CRM457-992: Change format period inline with prototype designs
  gems/laa_multi_step_forms/Gemfile.lock
  gems/laa_multi_step_forms/config/locales/en/helpers.yml
  gems/laa_multi_step_forms/spec/helpers/application_helper_spec.rb
  spec/presenters/nsm/check_answers/claim_details_card_spec.rb
Labels: approved

#616 CRM457-979: Correct back button on CYA/UFN pages
  app/services/decisions/back_decision_tree.rb
  app/views/prior_authority/steps/ufn/edit.html.erb
  spec/system/prior_authority/authority_value_spec.rb
  spec/system/prior_authority/check_your_answers/submission_spec.rb
  spec/system/prior_authority/ufn_spec.rb
Labels: approved

#617 Fix error page config
  config/routes.rb
Labels: approved

#620 Add workaround to missing translation issue and fix defendant card
  app/presenters/nsm/check_answers/base.rb
  app/presenters/nsm/check_answers/defendant_card.rb
  config/locales/en/nsm/check_answers.yml
  spec/presenters/nsm/check_answers/defendant_card_spec.rb
Labels: approved

#621 CRM457-1112: Don't try to create a bearer token if we don't have credentials
  .env.test
  app/services/app_store_token_provider.rb
  app/services/http_puller.rb
  app/services/submit_to_app_store/http_client.rb
  spec/services/app_store_token_provider_spec.rb
  spec/services/http_puller_spec.rb
  spec/services/submit_to_app_store/http_client_spec.rb
Labels: ready for review

#624 CRM457-1183: Fix exploding check answers page
  app/presenters/nsm/check_answers/base.rb
  app/presenters/nsm/check_answers/disbursement_costs_card.rb
  app/presenters/nsm/check_answers/work_items_card.rb
  spec/presenters/nsm/check_answers/disbursement_cost_card_spec.rb
  spec/presenters/nsm/check_answers/work_items_card_spec.rb
Labels: approved

#614 CRM457-1021: Autocompletes
  app/controllers/prior_authority/steps/case_detail_controller.rb
  app/forms/prior_authority/steps/case_detail_form.rb
  app/presenters/prior_authority/check_answers/case_detail_card.rb
  app/services/submit_to_app_store/prior_authority_payload_builder.rb
  app/views/prior_authority/steps/case_detail/edit.html.erb
  config/locales/en/errors.yml
  config/locales/en/prior_authority/offences.yml
  config/locales/en/prior_authority/prisons.yml
  db/migrate/20240229140805_add_main_offence_id_to_prior_authority_application.rb
  db/schema.rb
  spec/factories/prior_authority_application.rb
  spec/forms/prior_authority/steps/case_detail_form_spec.rb
  spec/presenters/prior_authority/check_answers/case_detail_card_spec.rb
  spec/services/submit_to_app_store/prior_authority_payload_builder_spec.rb
  spec/system/prior_authority/case_detail_spec.rb
  spec/system/support/prior_authority/step_helpers.rb
Labels: approved, In QA

#628 Crm457 867/ufn validation
  app/forms/nsm/steps/claim_type_form.rb
  app/forms/prior_authority/steps/ufn_form.rb
  app/validators/ufn_validator.rb
  config/locales/en/errors.yml
  config/locales/en/helpers.yml
  config/locales/en/prior_authority/steps.yml
  spec/factories/claims.rb
  spec/factories/prior_authority_application.rb
  spec/forms/prior_authority/steps/ufn_form_spec.rb
  spec/mailers/claim_submission_mailer_spec.rb
  spec/presenters/nsm/check_answers/claim_type_card_spec.rb
  spec/services/submit_to_app_store/nsm_payload_builder_spec.rb
  spec/services/submit_to_app_store/prior_authority_payload_builder_spec.rb
  spec/system/nsm/claim_type_spec.rb
  spec/system/prior_authority/application_lists_spec.rb
  spec/system/prior_authority/create_application_spec.rb
  spec/system/prior_authority/ufn_spec.rb
  spec/system/support/prior_authority/step_helpers.rb
  spec/validators/ufn_validator_spec.rb
Labels: approved

#630 CRM457-1101: Pull PA updates
  app/jobs/pull_updates.rb
  db/migrate/20240307165611_add_app_store_updated_at_to_prior_authority_application.rb
  db/schema.rb
  spec/jobs/pull_updates_spec.rb
Labels: approved

#636 CRM457-1214: Check gatekeeper when displaying start page links
  app/controllers/home_controller.rb
  app/services/providers/gatekeeper.rb
  app/views/home/index.en.html.erb
  config/gatekeeper.yml
  spec/factories/providers.rb
  spec/system/access_spec.rb
Labels: approved

#639 CRM457-992: Add custom item type specific cost error messages
  app/forms/prior_authority/quote_cost_validations.rb
  app/validators/item_type_dependant_validator.rb
  config/locales/en/errors.yml
  config/locales/en/prior_authority/alternative_quotes.yml
  spec/factories/prior_authority_application.rb
  spec/factories/quote.rb
  spec/system/prior_authority/alternative_quotes_spec.rb
  spec/system/prior_authority/service_cost_spec.rb
  spec/validators/item_type_dependant_validator_spec.rb
Labels: ready for review

#641 Move docker image scan to run in parrallel to tests
  .circleci/config.yml
Labels: approved

#642 [CRM457-984] Allow auto_grant status
  .env.development
  app/models/prior_authority_application.rb
  app/presenters/nsm/check_answers/application_status_card.rb
  config/locales/en/nsm/check_answers.yml
  config/locales/en/prior_authority.yml
Labels: approved

#643 [CRM457-1240] Process all pages when polling
  app/jobs/pull_updates.rb
  app/services/http_puller.rb
  spec/jobs/pull_updates_spec.rb
  spec/services/http_puller_spec.rb
Labels: approved

#648 Request Further Information: Update states allowed for applications and claims
  app/models/prior_authority_application.rb
Labels: approved

#633 CRM457-1001: View assessed applications
  app/controllers/prior_authority/applications_controller.rb
  app/forms/prior_authority/steps/additional_costs/detail_form.rb
  app/forms/prior_authority/steps/service_cost_form.rb
  app/forms/prior_authority/steps/travel_detail_form.rb
  app/helpers/allowed_value_helper.rb
  app/helpers/application_helper.rb
  app/helpers/tag_helper.rb
  app/jobs/pull_updates.rb
  app/models/prior_authority_application.rb
  app/presenters/prior_authority/check_answers/primary_quote_card.rb
  app/presenters/prior_authority/primary_quote_summary.rb
  app/services/app_store_client.rb
  app/services/http_puller.rb
  app/services/prior_authority/assessment_syncer.rb
  app/services/submit_to_app_store.rb
  app/services/submit_to_app_store/http_client.rb
  app/views/prior_authority/applications/frame_contents/_assessed.html.erb
  app/views/prior_authority/applications/show.html.erb
  app/views/prior_authority/applications/state_summaries/_auto_grant.html.erb
  app/views/prior_authority/applications/state_summaries/_granted.html.erb
  app/views/prior_authority/applications/state_summaries/_part_grant.html.erb
  app/views/prior_authority/applications/state_summaries/_rejected.html.erb
  app/views/prior_authority/applications/state_summaries/_submitted.html.erb
  app/views/prior_authority/steps/additional_costs/_subtable.html.erb
  app/views/prior_authority/steps/check_answers/_primary_quote.html.erb
  app/views/prior_authority/steps/check_answers/_primary_quote_details.html.erb
  app/views/prior_authority/steps/primary_quote_summary/_service_cost_subtable.html.erb
  app/views/prior_authority/steps/primary_quote_summary/_travel_cost_subtable.html.erb
  config/locales/en/prior_authority.yml
  config/locales/en/prior_authority/check_answers.yml
  config/locales/en/prior_authority/steps.yml
  db/migrate/20240312102142_add_base_cost_allowed_to_quotes.rb
  db/migrate/20240312123638_add_assessment_comment_to_prior_authority_applications.rb
  db/migrate/20240318102807_rename_base_adjustment_comment_to_service_adjustment_comment.rb
  db/schema.rb
  spec/helpers/application_helper_spec.rb
  spec/jobs/pull_updates_spec.rb
  spec/lib/tasks/submit_dummy_pa_data_spec.rb
  spec/services/app_store_client_spec.rb
  spec/services/http_puller_spec.rb
  spec/services/prior_authority/assessment_syncer_spec.rb
  spec/services/submit_to_app_store/http_client_spec.rb
  spec/services/submit_to_app_store_spec.rb
  spec/system/prior_authority/view_assessed_applications_spec.rb
Labels: approved, In QA

#653 CRM457-1102: Correct recipient for submitted notification
  app/mailers/prior_authority/submission_mailer.rb
  spec/mailers/prior_authority/submission_mailer_spec.rb
Labels: approved

#657 CRM457-1044: Send NSM defendant names separately
  app/services/submit_to_app_store/nsm_payload_builder.rb
  spec/services/submit_to_app_store/nsm_payload_builder_spec.rb
Labels: approved

#655 Crm457 1192 further info
  app/services/prior_authority/assessment_syncer.rb
  db/migrate/20240321145242_add_rfi_columns_to_prior_authority_application.rb
  db/schema.rb
  spec/factories/prior_authority_application.rb
  spec/services/prior_authority/assessment_syncer_spec.rb
Labels: approved

#658 CRM457-1033: Remove feedback URL from submission mailer
  app/mailers/nsm/submission_mailer.rb
  app/mailers/prior_authority/submission_mailer.rb
  spec/mailers/nsm/submission_mailer_spec.rb
  spec/mailers/prior_authority/submission_mailer_spec.rb
Labels: approved

#656 Do not inline sidekiq for bin/dev
  .env.development
  Procfile.dev
  config/initializers/sidekiq.rb
Labels: approved

#652 CRM457-1176 - Only allow service type to be set whn in draft
  app/forms/prior_authority/steps/primary_quote_form.rb
  app/views/prior_authority/steps/primary_quote/edit.html.erb
  spec/forms/prior_authority/steps/primary_quote_form_spec.rb
Labels: approved

#659 CRM457-1270: Use better status values
  app/models/claim.rb
  db/migrate/20240322122517_standardise_claim_statuses.rb
  db/schema.rb
  spec/controllers/nsm/steps/start_page_controller_spec.rb
Labels: approved

#660 CRM457-1239: Show expired applications (and fix date format)
  app/controllers/prior_authority/applications_controller.rb
  app/helpers/application_helper.rb
  app/helpers/tag_helper.rb
  app/models/prior_authority_application.rb
  app/services/prior_authority/assessment_syncer.rb
  app/views/prior_authority/applications/assessed.html.erb
  app/views/prior_authority/applications/frame_contents/_reviewed.html.erb
  app/views/prior_authority/applications/index.html.erb
  app/views/prior_authority/applications/response_summaries/_assessed.html.erb
  app/views/prior_authority/applications/response_summaries/_expired.html.erb
  app/views/prior_authority/applications/reviewed.html.erb
  app/views/prior_authority/applications/show.html.erb
  app/views/prior_authority/applications/state_summaries/_expired.html.erb
  config/initializers/time_formats.rb
  config/locales/en/prior_authority.yml
  config/routes.rb
  db/migrate/20240322141829_add_resubmission_dates_to_prior_authority_application.rb
  db/schema.rb
  spec/helpers/application_helper_spec.rb
  spec/presenters/nsm/check_answers/application_status_card_spec.rb
  spec/presenters/nsm/check_answers/case_details_card_spec.rb
  spec/presenters/nsm/check_answers/case_disposal_card_spec.rb
  spec/presenters/nsm/check_answers/claim_details_card_spec.rb
  spec/presenters/nsm/check_answers/claim_justification_card_spec.rb
  spec/presenters/nsm/check_answers/claim_type_card_spec.rb
  spec/presenters/nsm/check_answers/hearing_details_card_spec.rb
  spec/presenters/prior_authority/check_answers/client_detail_card_spec.rb
  spec/services/prior_authority/assessment_syncer_spec.rb
  spec/system/prior_authority/application_lists_spec.rb
  spec/system/prior_authority/view_assessed_applications_spec.rb
Labels: ready for review

#662 CRM457-1193: Add incorrect info review summary
  app/forms/prior_authority/steps/check_answers_form.rb
  app/models/prior_authority_application.rb
  app/presenters/tasks/generic.rb
  app/services/prior_authority/last_update_finder.rb
  app/views/prior_authority/steps/check_answers/edit.html.erb
  config/locales/en/errors.yml
  config/locales/en/prior_authority/check_answers.yml
  db/migrate/20240326074226_drop_confirmations_from_prior_authority_application.rb
  db/schema.rb
  spec/factories/prior_authority_application.rb
  spec/factories/supporting_documents.rb
  spec/forms/prior_authority/steps/check_answers_form_spec.rb
  spec/services/prior_authority/last_update_finder_spec.rb
  spec/services/submit_to_app_store/nsm_payload_builder_spec.rb
  spec/system/prior_authority/check_your_answers/sent_back_spec.rb
Labels: approved

#672 CRM457-1226: Add RFI card to CYA page
  app/controllers/prior_authority/steps/further_information_controller.rb
  app/presenters/prior_authority/check_answers/further_information_card.rb
  app/presenters/prior_authority/check_answers/report.rb
  app/services/prior_authority/last_update_finder.rb
  app/views/prior_authority/applications/response_summaries/_sent_back.html.erb
  config/locales/en/prior_authority.yml
  config/locales/en/prior_authority/check_answers.yml
  spec/factories/further_informations.rb
  spec/factories/prior_authority_application.rb
  spec/forms/prior_authority/steps/check_answers_form_spec.rb
  spec/presenters/prior_authority/check_answers/further_information_card_spec.rb
  spec/presenters/prior_authority/check_answers/report_spec.rb
  spec/services/prior_authority/last_update_finder_spec.rb
  spec/system/prior_authority/check_your_answers/sent_back_for_correct_info_spec.rb
  spec/system/prior_authority/check_your_answers/sent_back_for_further_info_spec.rb
Labels: ready for review

#674 CRM457-1277: Handle unrecognised office codes
  app/services/providers/gatekeeper.rb
  spec/services/providers/gatekeeper_spec.rb
Labels: ready for review

#675 Ensure PAA assessment sync errors do not block pull updates
  app/services/prior_authority/assessment_syncer.rb
  spec/jobs/pull_updates_spec.rb
Labels: ready for review

#677 Stop restricting hosts in development mode
  config/environments/development.rb
Labels: ready for review

#654 CRM457-1237: Single-screen office code selection in NSM and PA
  app/controllers/nsm/home_controller.rb
  app/controllers/nsm/offices_controller.rb
  app/controllers/nsm/steps/office/confirm_controller.rb
  app/controllers/nsm/steps/office/select_controller.rb
  app/controllers/offices_controller.rb
  app/controllers/prior_authority/offices_controller.rb
  app/forms/nsm/steps/office/confirm_form.rb
  app/forms/nsm/steps/office/select_form.rb
  app/forms/office_form.rb
  app/services/decisions/office_decision_tree.rb
  app/services/providers/office_router.rb
  app/views/home/index.en.html.erb
  app/views/nsm/steps/office/confirm/edit.html.erb
  app/views/nsm/steps/office/select/edit.html.erb
  app/views/offices/edit.html.erb
  config/locales/en/helpers.yml
  config/locales/en/nsm/steps.yml
  config/locales/en/offices.yml
  config/routes.rb
  spec/controllers/nsm/steps/provider_confirm_controller_spec.rb
  spec/controllers/nsm/steps/provider_select_controller_spec.rb
  spec/decisions/office_decision_tree_spec.rb
  spec/forms/nsm/steps/provider_confirm_form_spec.rb
  spec/forms/nsm/steps/provider_select_form_spec.rb
  spec/services/providers/office_router_spec.rb
  spec/system/accessibility_spec.rb
  spec/system/sign_in_spec.rb
Labels: approved, In QA

#679 CRM457-1272: Fix missing translation error
  app/presenters/nsm/check_answers/application_status_card.rb
  config/locales/en/nsm/check_answers.yml
  spec/presenters/nsm/check_answers/application_status_card_spec.rb
Labels: bug, approved

#678 CRM457-1271: Use real CSS classes
  app/views/nsm/steps/check_answers/show.html.erb
  app/views/nsm/steps/cost_summary/show.html.erb
  app/views/nsm/steps/view_claim/show.html.erb
Labels: bug, approved

#673 CRM457-1275 part 1: Detect changes on resubmission
  app/services/submit_to_app_store/prior_authority/event_builder.rb
  app/services/submit_to_app_store/prior_authority_payload_builder.rb
  spec/services/submit_to_app_store/prior_authority/event_builder_spec.rb
  spec/services/submit_to_app_store/prior_authority_payload_builder_spec.rb
Labels: approved
