Repository ministryofjustice/laa-submit-crime-forms, pull requests merged in 2024-12, with the labels that each got.

#1321 [CRM457-2291][CRM457-2293] add YCF case disposal summary views to CYA and view_claim reports
  app/presenters/nsm/check_answers/case_category_card.rb
  app/presenters/nsm/check_answers/read_only_report.rb
  app/presenters/nsm/check_answers/report.rb
  config/locales/en/nsm/check_answers.yml
  spec/presenters/nsm/check_answers/case_category_card_spec.rb
  spec/presenters/nsm/check_answers/read_only_report_spec.rb
  spec/presenters/nsm/check_answers/report_spec.rb
  spec/system/nsm/check_answers_spec.rb
  spec/system/nsm/view_claim_spec.rb
Labels: approved

#1327 CRM457-2288: Correctly check for YCF flow directions
  app/presenters/nsm/check_answers/read_only_report.rb
  app/presenters/nsm/check_answers/report.rb
Labels: approved

#1326 CRM457-2203: XML import
  .env.test
  app/controllers/concerns/claim_creatable.rb
  app/controllers/nsm/claims_controller.rb
  app/controllers/nsm/imports_controller.rb
  app/forms/nsm/import_form.rb
  app/presenters/app_store/v1/further_information.rb
  app/presenters/app_store/v1/nsm/claim.rb
  app/services/nsm/import_service.rb
  app/views/nsm/claims/index.html.erb
  app/views/nsm/imports/new.html.erb
  config/feature_flags.yml
  config/locales/en/nsm/claims.yml
  config/locales/en/nsm/imports.yml
  config/routes.rb
  spec/fixtures/files/import_sample.xml
  spec/fixtures/files/unreadable_import.xml
  spec/system/nsm/import_spec.rb
  spec/system/support/nsm/app_store_payload_helper.rb
Labels: approved, In QA

#1344 CRM457-2328: Account for translations in old NSM payloads
  app/controllers/nsm/steps/view_claim_controller.rb
  app/presenters/app_store/v1/nsm/claim.rb
  app/presenters/app_store/v1/nsm/disbursement.rb
  app/presenters/app_store/v1/nsm/disbursement_collection.rb
  app/presenters/app_store/v1/nsm/letter_or_call.rb
  app/presenters/app_store/v1/nsm/work_item.rb
  gems/laa_multi_step_forms/app/attributes/type/possibly_translated_array.rb
  gems/laa_multi_step_forms/app/attributes/type/possibly_translated_string.rb
  gems/laa_multi_step_forms/config/initializers/attribute_types.rb
  gems/laa_multi_step_forms/spec/attributes/type/possibly_translated_array_spec.rb
  gems/laa_multi_step_forms/spec/attributes/type/possibly_translated_string_spec.rb
Labels: approved

#1345 CRM457-2294: Remove incorrect warning
  app/views/nsm/steps/solicitor_declaration/edit.html.erb
  config/locales/en/nsm/steps.yml
Labels: ready for review

#1351 CRM457-2335: Stop doing local risk/value assessments
  app/services/risk_assessment/high_risk_assessment.rb
  app/services/risk_assessment/low_risk_assessment.rb
  app/services/risk_assessment/risk_assessment_scorer.rb
  app/services/submit_to_app_store/nsm_payload_builder.rb
  app/services/submit_to_app_store/prior_authority_payload_builder.rb
  spec/services/risk_assessment/high_risk_assessment_spec.rb
  spec/services/risk_assessment/low_risk_assessment_spec.rb
  spec/services/risk_assessment/risk_assessment_scorer_spec.rb
  spec/services/submit_to_app_store/nsm_payload_builder_spec.rb
  spec/services/submit_to_app_store/prior_authority_payload_builder_spec.rb
Labels: approved

#1353 Increase anomaly threshold
  helm_deploy/templates/ingress.yaml
Labels: ready for review

#1352 CRM457-2336: Add in missing AC from QA
  app/views/nsm/steps/view_claim/_adjustments.html.erb
  app/views/nsm/steps/view_claim/_allowed_additional_fees.html.erb
  app/views/nsm/steps/view_claim/additional_fees.html.erb
  config/locales/en/nsm/view_claim.yml
  spec/system/nsm/view_claim_spec.rb
Labels: ready for review, In QA

#1355 Use file_path instead of file_name for supporting documents
  app/presenters/app_store/v1/supporting_document.rb
  spec/system/prior_authority/view_applications_spec.rb
Labels: approved

#1356 CRM457-2347: Tighten the email regex
  app/validators/email_format_validator.rb
  spec/validators/email_format_validator_spec.rb
Labels: approved

#1357 CRM457-2217: Simplify event builder
  app/forms/prior_authority/steps/check_answers_form.rb
  app/jobs/submit_to_app_store.rb
  app/services/fixes/multiple_primary_quote_fixer.rb
  app/services/submit_to_app_store/payload_builder.rb
  app/services/submit_to_app_store/prior_authority/event_builder.rb
  app/services/submit_to_app_store/prior_authority_payload_builder.rb
  spec/jobs/submit_to_app_store_spec.rb
  spec/services/prior_authority/change_lister_spec.rb
  spec/services/submit_to_app_store/payload_builder_spec.rb
  spec/services/submit_to_app_store/prior_authority/event_builder_spec.rb
  spec/system/prior_authority/view_applications_spec.rb
Labels: approved

#1358 CRM457-2188: Remove previous mentions to eforms
  app/views/home/index.html.erb
  config/locales/en/submit_a_crime_form.yml
  gems/laa_multi_step_forms/config/locales/en/helpers.yml
Labels: approved

#1359 Bump actionpack from 7.1.4.1 to 7.1.5.1 in /gems/laa_multi_step_forms
  gems/laa_multi_step_forms/Gemfile.lock
Labels: ruby, approved

#1365 Bump common gem version
  Gemfile
  Gemfile.lock
Labels: approved

#1363 CRM457-2165: Tweak defendant deletion UI
  app/views/nsm/steps/defendant_delete/edit.html.erb
Labels: approved, In QA

#1367 CRM457-2273: If validation fails, calculation should not explode
  app/models/concerns/letters_and_calls_costs.rb
  spec/forms/nsm/steps/letters_calls_form_spec.rb
Labels: approved

#1364 CRM457-2177: Switch form field type to email
  app/views/nsm/steps/contact_details/edit.html.erb
  app/views/prior_authority/steps/case_contact/edit.html.erb
Labels: approved, In QA

#1370 CRM457-2277: Outsource S3 url generation to the gem
  Gemfile
  Gemfile.lock
  app/controllers/downloads_controller.rb
  spec/system/prior_authority/view_applications_spec.rb
Labels: approved

#1371 CRM457-2349: Improve form un-disabling
  app/javascript/handle-forms.js
Labels: approved

#1373 CRM457-2352: Renumber defendants on deletion
  app/forms/nsm/steps/defendant_delete_form.rb
  spec/forms/nsm/steps/defendants_delete_form_spec.rb
Labels: approved, In QA

#1376 Remove multi form gem: Remove dead references to /gem folder and adjust some comments (CRM457-2353)
  .rubocop.yml
  .sonarcloud.properties
  app/javascript/application.js
  app/presenters/nsm/tasks/base.rb
  spec/spec_helper.rb
Labels: approved

#1366 [CRM457-2171] align delete work items with LAA design
  app/views/nsm/steps/work_item_delete/edit.html.erb
  config/locales/en/nsm/steps.yml
Labels: ready for review

#1372 CRM457-2338: Add functionality to clone claims & applications
  app/controllers/concerns/claim_creatable.rb
  app/controllers/concerns/cloneable.rb
  app/controllers/concerns/generates_laa_reference.rb
  app/controllers/nsm/claims_controller.rb
  app/controllers/nsm/imports_controller.rb
  app/controllers/prior_authority/applications_controller.rb
  app/models/claim.rb
  app/models/firm_office.rb
  app/models/prior_authority_application.rb
  app/models/quote.rb
  app/models/solicitor.rb
  app/views/nsm/claims/index.html.erb
  app/views/prior_authority/applications/_drafts.html.erb
  config/locales/en/nsm/claims.yml
  config/locales/en/prior_authority.yml
  config/routes.rb
  spec/controllers/nsm/claims_controller_spec.rb
  spec/factories/claims.rb
  spec/factories/prior_authority_application.rb
  spec/models/quote_spec.rb
  spec/system/prior_authority/create_application_spec.rb
Labels: ready for review

#1374 CRM457-2307: Add net, vat, total to disbursement cost summary
  app/presenters/nsm/cost_summary/disbursements.rb
  config/locales/en/nsm/summary.yml
  spec/presenters/nsm/cost_summary/disbursements_spec.rb
Labels: approved, In QA

#1380 CRM457-2358: Add spec to test all the defined routes
  spec/system/production_spec.rb
Labels: ready for review
