Repository ministryofjustice/laa-submit-crime-forms, pull requests merged in 2024-09, with the labels that each got.

#1132 CRM457-1943: Caseworkers always see "Attendance with counsel" option
  app/services/submit_to_app_store/nsm_payload_builder.rb
  app/value_objects/work_types.rb
  spec/services/submit_to_app_store/nsm_payload_builder_spec.rb
Labels: approved, In QA

#1142 CRM457-1807: Standardise how we render the cost summary table
  app/presenters/nsm/check_answers/application_status_card.rb
  app/presenters/nsm/check_answers/cost_summary_card.rb
  app/presenters/nsm/cost_summary/report.rb
  app/presenters/nsm/cost_summary/summary.rb
  app/views/nsm/steps/cost_summary/_summary_table.html.erb
  app/views/nsm/steps/cost_summary/show.html.erb
  app/views/nsm/steps/view_claim/_cost_summary.html.erb
  config/locales/en/nsm/check_answers.yml
  config/locales/en/nsm/steps.yml
  spec/presenters/nsm/check_answers/cost_summary_card_spec.rb
  spec/presenters/nsm/cost_summary/report_spec.rb
  spec/presenters/nsm/cost_summary/summary_spec.rb
  spec/system/nsm/cost_summary_spec.rb
Labels: ready for review

#1140 CRM457-1947: More fixes to risk calculation
  app/services/risk_assessment/low_risk_assessment.rb
  spec/services/risk_assessment/low_risk_assessment_spec.rb
Labels: approved, In QA

#1125 CRM457-1863: Update tabs to sub-navigation
  app/views/nsm/claims/index.html.erb
  app/views/prior_authority/applications/_drafts.html.erb
  app/views/prior_authority/applications/index.html.erb
  config/locales/en/nsm/claims.yml
  config/locales/en/prior_authority.yml
Labels: approved, In QA

#1147 CRM457-1964: Stop changing LAA reference on every form submission
  app/forms/prior_authority/steps/ufn_form.rb
  spec/system/prior_authority/ufn_spec.rb
Labels: ready for review

#1148 CRM457-1965: Fix email address
  app/presenters/nsm/check_answers/application_status_card.rb
  config/application.rb
  spec/presenters/nsm/check_answers/application_status_card_spec.rb
Labels: ready for review

#1150 CRM457-1873: Retry app store subscription
  app/services/app_store_subscriber.rb
  spec/services/app_store_subscriber_spec.rb
Labels: approved

#1154 CRM457-1982: Handle situations where "old" incorrect information record has no 'sections changed'
  app/presenters/prior_authority/check_answers/incorrect_information_card.rb
Labels: approved

#1143 CRM457-1950: show granted adjustments
  app/models/claim.rb
  app/presenters/nsm/check_answers/application_status_card.rb
  app/presenters/nsm/check_answers/cost_summary_card.rb
  app/services/nsm/assessment_syncer.rb
  app/views/nsm/steps/view_claim/show.html.erb
  spec/jobs/pull_updates_spec.rb
  spec/presenters/nsm/check_answers/application_status_card_spec.rb
  spec/services/nsm/assessment_syncer_spec.rb
  spec/system/nsm/view_claim_spec.rb
Labels: approved, In QA

#1155 CRM457-1981: handle nil `allowed_total_cost_without_vat`
  app/views/nsm/steps/view_claim/_allowed_disbursements.html.erb
Labels: approved

#1152 CRM457-1962: Different limits for NSM and PA
  .env.development
  .env.test
  app/forms/concerns/document_uploadable.rb
  app/forms/concerns/prior_authority/document_uploadable.rb
  app/services/file_upload/file_uploader.rb
  app/views/nsm/steps/supporting_evidence/edit.html.erb
  app/views/prior_authority/steps/alternative_quote_details/edit.html.erb
  app/views/prior_authority/steps/further_information/edit.html.erb
  app/views/prior_authority/steps/primary_quote/edit.html.erb
  app/views/prior_authority/steps/reason_why/edit.html.erb
  app/views/shared/_multifile_upload.html.erb
  helm_deploy/templates/deployment-worker.yaml
  helm_deploy/templates/deployment.yaml
  helm_deploy/values-dev.yaml
  helm_deploy/values-prod.yaml
  helm_deploy/values-uat.yaml
  spec/forms/prior_authority/steps/primary_quote_form_spec.rb
  spec/system/prior_authority/primary_quote_spec.rb
Labels: approved, In QA

#1157 CRM457-1984: Cope with invalid items in quote cost calculations
  app/forms/prior_authority/steps/quote_cost_form.rb
  app/views/prior_authority/steps/service_cost/_items.html.erb
  spec/forms/prior_authority/steps/alternative_quotes/detail_form_spec.rb
Labels: approved

#1168 CRM457-1976: Remove cost summary from overview on view claim page
  app/controllers/nsm/steps/view_claim_controller.rb
  app/presenters/nsm/check_answers/read_only_report.rb
  spec/presenters/nsm/check_answers/read_only_report_spec.rb
  spec/system/nsm/view_claim_spec.rb
Labels: approved, In QA

#1162 CRM457-1940: Move footnote outside tab
  app/models/work_item.rb
  app/views/nsm/steps/view_claim/_allowed_work_items.html.erb
  app/views/nsm/steps/view_claim/show.html.erb
Labels: approved, In QA

#1169 CRM457-1989: Always show error summary at top of page
  app/views/nsm/steps/case_disposal/edit.html.erb
  app/views/nsm/steps/claim_type/edit.html.erb
  app/views/nsm/steps/defendant_delete/edit.html.erb
  app/views/nsm/steps/defendant_details/edit.html.erb
  app/views/nsm/steps/defendant_summary/edit.html.erb
  app/views/nsm/steps/disbursement_add/edit.html.erb
  app/views/nsm/steps/disbursement_cost/edit.html.erb
  app/views/nsm/steps/disbursement_delete/edit.html.erb
  app/views/nsm/steps/equality/edit.html.erb
  app/views/nsm/steps/equality_questions/edit.html.erb
  app/views/nsm/steps/firm_details/edit.html.erb
  app/views/nsm/steps/hearing_details/edit.html.erb
  app/views/nsm/steps/letters_calls/edit.html.erb
  app/views/nsm/steps/reason_for_claim/edit.html.erb
  app/views/nsm/steps/work_item/edit.html.erb
  app/views/nsm/steps/work_item_delete/edit.html.erb
  app/views/prior_authority/steps/alternative_quotes/_last_quote_deleted.html.erb
  app/views/prior_authority/steps/check_answers/edit.html.erb
  app/views/prior_authority/steps/further_information/edit.html.erb
Labels: approved, In QA

#1170 CRM457-1991: Remove boxes from tab contents
  app/views/prior_authority/applications/index.html.erb
Labels: approved, In QA

#1175 CRM457-1967: Mark new FIs in payload
  Dockerfile
  Gemfile
  Gemfile.lock
  app/models/prior_authority_application.rb
  app/services/app_store_update_processor.rb
  app/services/submit_to_app_store/prior_authority/further_informations_payload_builder.rb
  app/services/submit_to_app_store/prior_authority/incorrect_informations_payload_builder.rb
  spec/jobs/pull_updates_spec.rb
  spec/services/app_store_update_processor_spec.rb
  spec/services/submit_to_app_store/prior_authority_payload_builder_spec.rb
Labels: approved

#1156 CRM457-1669: Add PDF of claims
  app/controllers/nsm/steps/view_claim_controller.rb
  app/presenters/nsm/allowed_work_items/summary_table.rb
  app/presenters/nsm/allowed_work_items/table.rb
  app/presenters/nsm/check_answers/application_status_card.rb
  app/presenters/nsm/check_answers/cost_summary_card.rb
  app/presenters/nsm/check_answers/read_only_report.rb
  app/services/pdf_service.rb
  app/views/nsm/steps/view_claim/_adjustments.html.erb
  app/views/nsm/steps/view_claim/_allowed_disbursements.html.erb
  app/views/nsm/steps/view_claim/_allowed_letters_and_calls.html.erb
  app/views/nsm/steps/view_claim/_allowed_work_items.html.erb
  app/views/nsm/steps/view_claim/_disbursements.html.erb
  app/views/nsm/steps/view_claim/_letters_and_calls.html.erb
  app/views/nsm/steps/view_claim/_section.html.erb
  app/views/nsm/steps/view_claim/_work_items.html.erb
  app/views/nsm/steps/view_claim/pdf.html.erb
  app/views/nsm/steps/view_claim/show.html.erb
  config/locales/en/nsm/view_claim.yml
  config/routes.rb
  spec/presenters/nsm/allowed_work_items/summary_table_spec.rb
  spec/presenters/nsm/allowed_work_items/table_spec.rb
  spec/presenters/nsm/check_answers/cost_summary_card_spec.rb
  spec/system/nsm/view_claim_spec.rb
Labels: approved, In QA

#1176 CRM457-1975: Onboard CRM7 tranche 5 - 17/09/2024
  config/gatekeeper_crm7.yml
Labels: approved

#1178 CRM457-2024: Validate disbursement add screen
  app/forms/nsm/steps/disbursement_add_form.rb
  config/locales/en/errors.yml
  spec/system/nsm/disbursements_spec.rb
Labels: ready for review

#1173 [CRM457-1990] Print instruction on claim complete
  app/views/nsm/steps/claim_confirmation/show.html.erb
  config/locales/en/nsm/steps.yml
Labels: approved

#1185 CRM457-1583: Replace incorrect_information_explanation
  app/forms/prior_authority/steps/check_answers_form.rb
  app/services/prior_authority/assessment_syncer.rb
  app/views/prior_authority/steps/check_answers/edit.html.erb
  db/migrate/20240603125345_create_incorrect_informations.rb
  db/migrate/20240918093306_remove_incorrect_information_explanation_from_application.rb
  db/schema.rb
  lib/test_data/pa_resubmitter.rb
  spec/factories/prior_authority_application.rb
  spec/services/prior_authority/assessment_syncer_spec.rb
  spec/services/submit_to_app_store/prior_authority_payload_builder_spec.rb
  spec/system/prior_authority/check_your_answers/sent_back_for_correct_info_spec.rb
  spec/system/prior_authority/view_applications_spec.rb
Labels: approved

#1186 CRM457-1817: Reduce idle timeout to 1 hour
  config/application.rb
  config/initializers/devise.rb
Labels: approved, In QA

#1187 CRM457-1888: Adjust court wordings
  app/forms/nsm/steps/case_transfer_form.rb
  app/forms/nsm/steps/claim_type_form.rb
  app/forms/nsm/steps/court_area_form.rb
  app/forms/nsm/steps/office_area_form.rb
  app/models/concerns/stage_reached_calculatable.rb
  app/presenters/nsm/tasks/claim_type.rb
  app/views/nsm/steps/case_transfer/edit.html.erb
  app/views/nsm/steps/hearing_details/edit.html.erb
  config/locales/en/errors.yml
  config/locales/en/helpers.yml
  config/locales/en/nsm/steps.yml
  db/migrate/20240918145718_rename_transferred_from_to_transferred_to.rb
  db/schema.rb
  spec/forms/nsm/steps/claim_type_form_spec.rb
  spec/forms/nsm/steps/court_area_form_spec.rb
  spec/forms/nsm/steps/office_area_form_spec.rb
  spec/presenter/nsm/steps/claim_type_presenter_spec.rb
  spec/services/submit_to_app_store/nsm_payload_builder_spec.rb
  spec/system/nsm/prog_and_prom_spec.rb
Labels: approved, In QA

#1196 CRM457-2006: NSM expiry
  app/models/claim.rb
  app/models/further_information.rb
  app/models/prior_authority_application.rb
  app/presenters/concerns/further_information_presentable.rb
  app/presenters/nsm/check_answers/application_status_card.rb
  app/presenters/nsm/check_answers/further_information_card.rb
  app/presenters/nsm/check_answers/read_only_report.rb
  app/presenters/prior_authority/check_answers/compact_further_information_card.rb
  app/services/auditor.rb
  app/services/nsm/assessment_syncer.rb
  app/views/nsm/steps/view_claim/show.html.erb
  config/locales/en/nsm/check_answers.yml
  config/locales/en/nsm/claims.yml
  config/locales/en/nsm/view_claim.yml
  db/migrate/20240924081716_make_further_informations_polymorphic.rb
  db/migrate/20240924090158_add_resubmission_deadline_to_further_informations.rb
  db/schema.rb
  spec/factories/prior_authority_application.rb
  spec/presenters/nsm/check_answers/read_only_report_spec.rb
  spec/system/nsm/view_claim_spec.rb
  spec/system/prior_authority/view_applications_spec.rb
Labels: approved

#1195 CRM457-1755: SolidCache
  Gemfile
  Gemfile.lock
  config/cache.yml
  config/environments/production.rb
  db/migrate/20240923091317_add_cache_table.rb
  db/schema.rb
Labels: approved

#1191 CRM457-2033: Accept new translation format - MERGE THIS FIRST
  app/services/nsm/assessment_syncer.rb
  app/views/nsm/steps/equality/edit.html.erb
  spec/services/nsm/assessment_syncer_spec.rb
Labels: approved

#1205 CRM457-2069: Add exceptionAdd exception
  helm_deploy/templates/ingress.yaml
Labels: ready for review

#1206 CRM457-2045: Add update links to incomplete items
  app/presenters/nsm/work_items_row.rb
  app/views/nsm/steps/disbursements/edit.html.erb
  config/locales/en/nsm/steps.yml
  config/locales/en/nsm/steps/work_items.yml
  spec/system/nsm/disbursements_spec.rb
Labels: approved, In QA

#1208 CRM457-1759: DB SSL mode
  config/database.yml
  helm_deploy/templates/deployment-worker.yaml
  helm_deploy/templates/deployment.yaml
Labels: approved

#1209 CRM457-2100: Fix sorting
  app/models/claim.rb
  spec/models/claim_spec.rb
Labels: ready for review

#1210 CRM457-2083: Add cost summary to claim payload
  app/presenters/nsm/check_answers/cost_summary_card.rb
  app/services/submit_to_app_store/nsm_payload_builder.rb
  spec/presenters/nsm/check_answers/cost_summary_card_spec.rb
  spec/services/submit_to_app_store/nsm_payload_builder_spec.rb
Labels: ready for review
