Repository ministryofjustice/laa-submit-crime-forms, pull requests merged in 2024-07, with the labels that each got.

#965 CRM457-1349: Stop modsec rejecting large files
  helm_deploy/templates/ingress.yaml
Labels: approved

#966 Configure sidekiq to use specific database locally
  config/initializers/sidekiq.rb
Labels: approved

#967 CRM457-1696: Amend content for when no adjustments of type exist
  app/views/nsm/steps/view_claim/allowed_work_items.html.erb
  config/locales/en/nsm/view_claim.yml
Labels: approved

#964 CRM457-1705: Do not show links to documents on PDFs
  app/controllers/prior_authority/applications_controller.rb
  app/presenters/prior_authority/check_answers/compact_further_information_card.rb
  app/presenters/prior_authority/check_answers/primary_quote_card.rb
  app/presenters/prior_authority/check_answers/reason_why_card.rb
  app/presenters/prior_authority/check_answers/report.rb
  app/views/prior_authority/applications/_application_details.html.erb
  app/views/prior_authority/applications/pdf.html.erb
  app/views/prior_authority/applications/response_summaries/_sent_back.html.erb
  app/views/prior_authority/steps/alternative_quote_details/confirm_delete.html.erb
  app/views/prior_authority/steps/alternative_quotes/_quote_summary.html.erb
  app/views/prior_authority/steps/alternative_quotes/_with_alternative_quotes.html.erb
  app/views/prior_authority/steps/check_answers/_alternative_quotes.html.erb
  spec/system/prior_authority/view_applications_spec.rb
Labels: approved, In QA

#972 CRM457-1693: Fix tag colour
  config/locales/en/nsm/claims.yml
  spec/presenters/nsm/check_answers/application_status_card_spec.rb
Labels: approved, In QA

#952 [CRM457-1625] CRM4 Provider: Amendments to service tables/ fields
  app/views/prior_authority/steps/additional_costs/_subtable.html.erb
  app/views/prior_authority/steps/alternative_quote_details/edit.html.erb
  app/views/prior_authority/steps/delete_travel/edit.html.erb
  app/views/prior_authority/steps/primary_quote_summary/_service_cost_subtable.html.erb
  app/views/prior_authority/steps/primary_quote_summary/_travel_cost_subtable.html.erb
  app/views/prior_authority/steps/service_cost/_items.html.erb
  app/views/prior_authority/steps/service_cost/_time.html.erb
  config/locales/en/prior_authority/alternative_quotes.yml
  config/locales/en/prior_authority/steps.yml
  spec/system/prior_authority/service_cost_spec.rb
  spec/system/prior_authority/travel_detail_spec.rb
  spec/system/support/prior_authority/step_helpers.rb
Labels: approved, In QA

#974 CRM457-1684 04/07 CRM5 EoUL Onboard Tranche 6 (All providers)
  config/gatekeeper_crm5.yml
Labels: approved

#973 CRM457-1529: Change snyk docker scanning approach
  .circleci/config.yml
  app/controllers/nsm/steps/view_claim_controller.rb
Labels: approved

#979 CMR457-1724: Use snyk to test IaC/helm templates
  .circleci/config.yml
  helm_deploy/templates/tests/test-connection.yaml
Labels: approved

#976 CRM457-1720: UI if additional cost removed
  app/views/prior_authority/steps/primary_quote_summary/_additional_cost_card.html.erb
  spec/system/prior_authority/additional_costs_spec.rb
Labels: approved, In QA

#978 CRM457-1725: Remove inaccurate reference to printing
  app/views/nsm/steps/claim_confirmation/show.html.erb
  config/locales/en/nsm/steps.yml
Labels: approved, In QA

#977 CRM457-1695: Change 'application' to 'claim'
  config/locales/en/nsm/steps.yml
  spec/system/nsm/office_code_spec.rb
Labels: approved

#984 CRM457-1672: Try to avoid migration races
  lib/tasks/db.rake
  run.sh
Labels: approved

#986 CRM457-1660: Use internal hostname to bypass modsec
  .env.development
  app/services/app_store_subscriber.rb
  config/environments/production.rb
  helm_deploy/templates/_helpers.tpl
  helm_deploy/templates/deployment.yaml
  spec/services/app_store_subscriber_spec.rb
Labels: approved

#990 Get dependabot to update docker dependencies
  .github/dependabot.yml
Labels: approved

#985 WIP: Crm457 1697/work completed date
  app/forms/nsm/steps/claim_details_form.rb
  app/presenters/nsm/check_answers/claim_details_card.rb
  app/views/nsm/steps/claim_details/edit.html.erb
  config/locales/en/errors.yml
  config/locales/en/helpers.yml
  config/locales/en/nsm/check_answers.yml
  db/migrate/20240709103203_add_work_completed_date.rb
  db/schema.rb
  spec/factories/claims.rb
  spec/forms/nsm/steps/claim_details_form_spec.rb
  spec/presenters/nsm/check_answers/claim_details_card_spec.rb
  spec/services/submit_to_app_store/nsm_payload_builder_spec.rb
  spec/system/nsm/claim_details_spec.rb
Labels: approved

#993 CRM457-1368: Unsubscribe on close PR
  .github/actions/delete-dev-release/action.yml
  app/services/app_store_client.rb
  app/services/app_store_subscriber.rb
  config/application.rb
  lib/tasks/app_store.rake
  spec/lib/tasks/app_store_unsubscribe_spec.rb
  spec/services/app_store_client_spec.rb
  spec/services/app_store_subscriber_spec.rb
Labels: ready for review

#998 CRM457-1747: Add task to fix applications with multiple primary quotes
  app/jobs/submit_to_app_store.rb
  app/services/fixes/multiple_primary_quote_fixer.rb
  app/services/submit_to_app_store/payload_builder.rb
  app/services/submit_to_app_store/prior_authority_payload_builder.rb
  lib/tasks/fixes.rake
  spec/jobs/submit_to_app_store_spec.rb
  spec/lib/tasks/fixes_spec.rb
  spec/services/fixes/multiple_primary_quote_fixer_spec.rb
  spec/services/submit_to_app_store/payload_builder_spec.rb
Labels: approved

#994 CRM457-1744: Allow downloading files with weird chars in them
  app/controllers/prior_authority/downloads_controller.rb
  spec/system/prior_authority/view_applications_spec.rb
Labels: ready for review

#999 CRM457-1721: Remove modsec false positives
  helm_deploy/templates/ingress.yaml
Labels: ready for review

#1008 Pull latest AWS RDS certs
  Dockerfile
Labels: approved

#1010 Onboard additional providers for CRM4 (TRANCHE 8)
  config/gatekeeper_crm4.yml
Labels: approved

#1020 CRM457-1771: Remove all vestigial activestorage stuff
  app/models/supporting_document.rb
  db/migrate/20240725152523_remove_active_storage_tables.rb
  db/schema.rb
  spec/controllers/nsm/steps/supporting_evidence_controller_spec.rb
Labels: ready for review

#1019 CRM457-1783: Multiple FIs
  app/services/prior_authority/assessment_syncer.rb
  spec/controllers/nsm/steps/defendants_delete_controller_spec.rb
  spec/controllers/nsm/steps/disbursements_delete_controller_spec.rb
  spec/controllers/nsm/steps/work_items_delete_controller_spec.rb
Labels: approved, In QA

#1023 CRM457-1633: Update the inactive office code list
  config/inactive_offices.yml
Labels: ready for review

#1021 [CRM457-1777] Onboard additional providers (TRANCHE 9)
  config/gatekeeper_crm4.yml
Labels: DO NOT MERGE
