Repository ministryofjustice/laa-submit-crime-forms, pull requests merged in 2025-03, with the labels that each got.

#1423 Return all XML validation errors
  app/services/nsm/importers/xml/import_service.rb
Labels: approved, In QA

#1433 Introduce a new XML errors summary
  .circleci/config.yml
  .rubocop.yml
  Dockerfile
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/custom/alert.scss
  app/controllers/nsm/imports_controller.rb
  app/controllers/nsm/steps/defendant_details_controller.rb
  app/controllers/steps/base_step_controller.rb
  app/presenters/nsm/check_answers/application_status_card.rb
  app/services/compression_service.rb
  app/services/nsm/assessment_syncer.rb
  app/services/nsm/importers/xml/import_service.rb
  app/services/pdf_service.rb
  app/views/nsm/imports/errors.html.erb
  app/views/nsm/imports/new.html.erb
  app/views/shared/_alert.html.erb
  app/views/shared/_flash_banner.html.erb
  bin/snyk-formatted
  config/locales/en/nsm/imports.yml
  config/routes.rb
  spec/services/compression_service_spec.rb
  spec/services/nsm/importers/xml/v1/importer_spec.rb
  spec/system/nsm/import_spec.rb
Labels: ready for review

#1442 CRM457-2458: Adjust the 'Import a claim' page
  Gemfile.lock
  app/views/nsm/imports/new.html.erb
  config/locales/en/nsm/imports.yml
Labels: ready for review

#1451 CRM457-2458 Adds error message to Import a claim
  app/controllers/nsm/imports_controller.rb
  app/forms/nsm/import_form.rb
  app/views/nsm/claims/index.html.erb
  app/views/nsm/imports/new.html.erb
  config/locales/en/nsm/imports.yml
  spec/forms/nsm/import_form_spec.rb
  spec/system/nsm/import_spec.rb
Labels: ready for review

#1453 Enable new Import a Claim flow in UAT/Production
  config/feature_flags.yml
Labels: approved, ready for review

#1456 Add a test case to handle broken XML
  spec/fixtures/files/unmatched_fields.xml
  spec/system/nsm/import_spec.rb
Labels: approved

#1468 Show all service types when the box is focused even when empty
  app/javascript/autocomplete.js
  app/views/prior_authority/steps/primary_quote/edit.html.erb
Labels: approved
