Repository ministryofjustice/laa-submit-crime-forms, pull requests merged in 2025-01, with the labels that each got.

#1401 [CRM457-1792] bump common gem
  Gemfile
  Gemfile.lock
Labels: approved

#1394 [CRM457-2376] - NSM Provider Update Overview Page to Show Supporting Documents Have Been Deleted
  app/models/claim.rb
  app/presenters/app_store/v1/nsm/claim.rb
  app/presenters/concerns/further_information_presentable.rb
  app/presenters/nsm/check_answers/evidence_uploads_card.rb
  app/presenters/nsm/check_answers/further_information_card.rb
  app/presenters/nsm/check_answers/read_only_report.rb
  app/views/nsm/steps/view_claim/_gdpr_uploaded_files_deleted.html.erb
  config/locales/en/nsm/view_claim.yml
  spec/presenters/nsm/check_answers/evidence_upload_card_spec.rb
  spec/presenters/nsm/check_answers/further_information_card_spec.rb
Labels: ready for review

#1398 CRM457-2374: Add service to handle draft GDPR claims
  Gemfile
  Gemfile.lock
  app/controllers/nsm/steps/supporting_evidence_controller.rb
  app/jobs/delete_draft_documents.rb
  app/services/delete_document_service.rb
  app/services/file_upload/aws_file_uploader.rb
  app/services/file_upload/base_file_uploader.rb
  app/services/file_upload/file_uploader.rb
  app/services/file_upload/local_file_uploader.rb
  config/schedule.yml
  config/sidekiq.yml
  db/migrate/20250116141825_add_documents_deleted_to_claims.rb
  db/pii.yml
  db/schema.rb
  spec/jobs/delete_draft_documents_spec.rb
  spec/services/delete_document_service_spec.rb
  spec/services/file_upload/aws_file_uploader_spec.rb
  spec/services/file_upload/base_file_uploader_spec.rb
  spec/services/file_upload/local_file_uploader_spec.rb
  spec/services/submit_to_app_store/nsm_payload_builder_spec.rb
Labels: ready for review

#1404 CRM457-2405 Updates feedback link
  config/application.rb
Labels: DO NOT MERGE, approved

#1405 Fixes template rendering logic
  app/views/prior_authority/applications/_application_details.html.erb
Labels: approved
